#!/usr/bin/env bash
# Regenerate CHANGES.md from `git log`. Groups every
# commit on `main` by authored date (YYYY-MM-DD) in
# reverse chronological order, one subject line per
# bullet. For the curated per-release retrospective,
# see CHANGELOG.md; for long-form saga narratives, see
# docs/saga.md.
#
# Run from the repo root (or anywhere -- the script cds
# to the repo root itself) and commit the result.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

{
  cat <<'EOF'
# Changes

Reverse-chronological log of every commit on `main`.
Autogenerated from `git log` by
[`scripts/gen-changes.sh`](scripts/gen-changes.sh);
regenerate and commit whenever you want the list
refreshed.

For the curated per-release retrospective (scope, test
counts, deferred follow-ups), see
[`CHANGELOG.md`](CHANGELOG.md). For long-form saga
narratives, see [`docs/saga.md`](docs/saga.md).

EOF

  # Transliterate non-ASCII in historical commit subjects (em/en
  # dashes, curly quotes, arrows, ellipsis) so the generated file
  # passes the ASCII-only markdown gate without rewriting history.
  git log --pretty=format:'%ai%x09%s' \
    | perl -CSD -pe 's/\x{2014}/--/g; s/\x{2013}/-/g;
        s/[\x{2018}\x{2019}]/\x27/g; s/[\x{201C}\x{201D}]/"/g;
        s/\x{2192}/->/g; s/\x{2190}/<-/g; s/\x{2026}/.../g;
        s/[^\x00-\x7F]/?/g' \
    | awk -F '\t' '
    {
      date = substr($1, 1, 10)
      subject = $2
      if (date != last) {
        printf "\n## %s\n\n", date
        last = date
      }
      printf "- %s\n", subject
    }
  '
  echo
} > CHANGES.md

echo "Wrote $(wc -l < CHANGES.md | tr -d " ") lines to CHANGES.md"
