⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 18.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID CALC
FNS←'*⍟÷|QSCT'
∇DESCRIBE
'CALC -- NUMERICAL CALCULUS ON A FUNCTION NAMED BY A CHARACTER'
'FROM THE TABLE FNS, OR GIVEN AS A POLYNOMIAL, HIGHEST POWER'
'FIRST, AS POLY WRITES THEM.'
''
'   F AT X          F AT X, X A NUMBER OR A VECTOR.'
'   A INTEG F       THE INTEGRAL OF F OVER A[1] TO A[2] IN A[3]'
'                   STEPS, BY SIMPSON''S RULE.'
'   H INTEGV Y      THE INTEGRAL OF A TABLE OF VALUES Y, STEP H.'
'   F DERIV X       THE DERIVATIVE OF F AT X.'
'   F NEWTON X      A ROOT OF F, BY NEWTON FROM X.'
'   F BISECT A      A ROOT OF F BETWEEN A[1] AND A[2].'
'   SERIES T        E, PI AND SIN 1 BY THEIR SERIES TO WITHIN T,'
'                   BESIDE THE PRIMITIVES.'
''
'THE CHARACTERS OF FNS: * EXPONENTIAL, ⍟ LOGARITHM, ÷ RECIPROCAL,'
'| MAGNITUDE, Q SQUARE ROOT, S SINE, C COSINE, T TANGENT. TYPE'
'HOWCALC FOR MORE.'
∇
∇HOWCALC
'THIS APL HAS NO WAY TO HAND ONE FUNCTION TO ANOTHER, SO A'
'FUNCTION IS NAMED: ONE CHARACTER OF FNS, WHICH AT TURNS INTO'
'THE PRIMITIVE BY A TABLE, OR A VECTOR OF COEFFICIENTS, WHICH'
'AT EVALUATES AS A POLYNOMIAL. ''S'' AT 1 IS THE SINE OF 1; 1 0 0'
'AT 3 IS 9.'
''
'INTEG IS SIMPSON''S RULE: THE VALUES AT EVENLY SPACED POINTS'
'WEIGHTED 1 4 2 4 ... 2 4 1, TIMES A THIRD OF THE STEP; A[3]'
'IS MADE EVEN IF IT IS NOT. IT IS EXACT FOR A CUBIC. INTEGV'
'DOES THE SAME OVER VALUES YOU SUPPLY, BY SIMPSON WHEN THERE'
'IS AN ODD NUMBER OF THEM AND BY THE TRAPEZIUM RULE WHEN NOT.'
''
'DERIV IS THE CENTRAL DIFFERENCE OVER A STEP OF 1E¯5. NEWTON'
'STEPS X BY MINUS F OVER THAT DERIVATIVE UNTIL THE STEP IS'
'UNDER 1E¯12, AT MOST FIFTY TIMES. BISECT HALVES THE INTERVAL'
'SIXTY TIMES, WHICH NEEDS F TO CHANGE SIGN ACROSS IT; IF IT'
'DOES NOT, BISECT SAYS SO AND GIVES A[1].'
''
'SERIES ADDS TERMS UNTIL ONE IS SMALLER THAN T: FOR E, THE'
'RECIPROCAL FACTORIALS; FOR PI, NILAKANTHA''S 3+4÷2×3×4 LESS'
'4÷4×5×6 AND SO ON; FOR SIN 1, THE ODD POWERS OVER THEIR'
'FACTORIALS WITH ALTERNATING SIGNS. EACH LINE GIVES THE SUM,'
'THE TERMS TAKEN, AND THE PRIMITIVE''S VALUE TO COMPARE.'
∇
∇R←F AT X
⍝ F AT X: A CHARACTER OF FNS BY THE TABLE, A NUMERIC VECTOR AS A
⍝ POLYNOMIAL, HIGHEST POWER FIRST.
→(0=1↑0⍴F)/POLY
→(EXP,LN,RECIP,MAG,ROOT,SIN,COS,TAN)[FNS⍳F]
EXP:R←*X
→0
LN:R←⍟X
→0
RECIP:R←÷X
→0
MAG:R←|X
→0
ROOT:R←X*0.5
→0
SIN:R←1○X
→0
COS:R←2○X
→0
TAN:R←3○X
→0
POLY:R←(X∘.*⌽¯1+⍳⍴F←,F)+.×F
∇
∇R←A INTEG F;N;H;X
⍝ SIMPSON'S RULE OVER A[1] TO A[2] IN A[3] STEPS, MADE EVEN.
N←2×⌈A[3]÷2
H←(A[2]-A[1])÷N
X←A[1]+H×0,⍳N
R←(H÷3)×+/(F AT X)×1,((N-1)⍴4 2),1
∇
∇R←H INTEGV Y;N
⍝ SIMPSON OVER AN ODD NUMBER OF VALUES, THE TRAPEZIUM RULE OVER AN
⍝ EVEN NUMBER.
N←×/⍴Y←,Y
→(0=2|N)/TRAP
R←(H÷3)×+/Y×1,((N-2)⍴4 2),1
→0
TRAP:R←H×(+/Y)-0.5×Y[1]+Y[N]
∇
∇R←F DERIV X;H
H←1E¯5
R←((F AT X+H)-F AT X-H)÷2×H
∇
∇R←F NEWTON X;S;K
K←0
L:S←(F AT X)÷F DERIV X
X←X-S
K←K+1
→((K<50)∧1E¯12<|S)/L
R←X
∇
∇R←F BISECT A;LO;HI;M;K
LO←A[1]
HI←A[2]
R←LO
→(0<(×F AT LO)××F AT HI)/NOSIGN
K←0
L:M←(LO+HI)÷2
→(0=F AT M)/FOUND
→((×F AT M)=×F AT LO)/UP
HI←M
→NEXT
UP:LO←M
NEXT:K←K+1
→(K<60)/L
FOUND:R←M
→0
NOSIGN:'F HAS THE SAME SIGN AT BOTH ENDS; NO ROOT IS BRACKETED.'
∇
∇SERIES T;E;P;S
E←ESERIES T
P←PISERIES T
S←1 SINSERIES T
'E      ';E[1];' IN ';E[2];' TERMS; *1 IS ';*1
'PI     ';P[1];' IN ';P[2];' TERMS; ○1 IS ';○1
'SIN 1  ';S[1];' IN ';S[2];' TERMS; 1○1 IS ';1○1
∇
∇R←ESERIES T;K;V
⍝ THE SUM OF 1÷!K FROM K OF 0 UNTIL A TERM IS UNDER T; THE SUM AND
⍝ THE TERMS TAKEN.
K←0
R←0
L:V←÷!K
R←R+V
K←K+1
→(V≥T)/L
R←R,K
∇
∇R←PISERIES T;K;V
⍝ NILAKANTHA: 3, THEN 4 OVER THE PRODUCT OF THREE CONSECUTIVE
⍝ NUMBERS FROM 2, ALTERNATELY ADDED AND TAKEN, UNTIL A TERM IS
⍝ UNDER T.
K←0
R←3
L:K←K+1
V←4÷×/(2×K)+0 1 2
R←R+V×¯1*K+1
→(V≥T)/L
R←R,K+1
∇
∇R←X SINSERIES T;K;V
⍝ X, LESS X*3 OVER !3, PLUS X*5 OVER !5, UNTIL A TERM IS UNDER T.
K←0
R←0
L:V←(X*1+2×K)÷!1+2×K
R←R+V×¯1*K
K←K+1
→((|V)≥T)/L
R←R,K
∇
