⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 20.30.00 09/24/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID COURSE
GO←'GO'
LAST←0
STOP←'STOP'
∇DESCRIBE
'COURSE -- APL, LESSON BY LESSON, WITH QUIZZES.'
''
'   START       BEGIN AT LESSON 1.'
'   CONTENTS    THE LESSONS, BY NUMBER AND TITLE.'
'   LESSON N    READ LESSON N.'
'   NEXT        THE LESSON AFTER THE LAST ONE YOU READ.'
'   QUIZ N      QUESTIONS ON LESSON N, MARKED AS YOU GO.'
''
'A LESSON PAUSES BETWEEN SECTIONS SO YOU CAN TRY WHAT IT'
'SHOWS: AT A PAUSE, TYPE AN EXPRESSION OR A SYSTEM COMMAND,'
'GO TO GO ON, OR STOP TO LEAVE A LESSON OR A QUIZ.'
∇
∇CONTENTS
'THE LESSONS. LESSON N READS ONE; QUIZ N ASKS ABOUT IT.'
''
'   1  WHERE YOU ARE'
'   2  NUMBERS'
'   3  VECTORS'
'   4  COMPARISON AND LOGIC'
'   5  REDUCTION AND SCAN'
'   6  SELECTION'
'   7  MATRICES'
'   8  PRODUCTS'
'   9  ORDER AND COUNTING'
'  10  CHARACTERS'
'  11  DEFINING FUNCTIONS'
'  12  BRANCHING'
'  13  INPUT AND OUTPUT'
'  14  ERRORS'
'  15  WORKSPACES'
'  16  THE TWO MODES'
∇
∇START
LESSON 1
∇
∇NEXT
→(LAST≥16)/END
LESSON LAST+1
→0
END:'THAT WAS THE LAST LESSON. CONTENTS LISTS THEM ALL.'
∇
∇LESSON ∆N
⍝ LAST IS GLOBAL ON PURPOSE: NEXT READS IT, AND )SAVE KEEPS IT.
⍝ THE LOCALS OF EVERYTHING ON THE WAY TO A PAUSE ARE DELTA NAMES,
⍝ SO THAT WHAT THE READER TYPES THERE SEES THEIR OWN NAMES.
→((∆N<1)∨∆N>16)/BAD
LAST←∆N
→(∆N>10)/NOTYET
→(L1,L2,L3,L4,L5,L6,L7,L8,L9,L10)[∆N]
L1:∆L1
→0
L2:∆L2
→0
L3:∆L3
→0
L4:∆L4
→0
L5:∆L5
→0
L6:∆L6
→0
L7:∆L7
→0
L8:∆L8
→0
L9:∆L9
→0
L10:∆L10
→0
NOTYET:'LESSON ';∆N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇QUIZ ∆N
→((∆N<1)∨∆N>16)/BAD
→(∆N>10)/NOTYET
'QUIZ ';∆N;'. TYPE EACH ANSWER AS APL AFTER THE QUAD PROMPT.'
→(Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10)[∆N]
Q1:∆Q1
→0
Q2:∆Q2
→0
Q3:∆Q3
→0
Q4:∆Q4
→0
Q5:∆Q5
→0
Q6:∆Q6
→0
Q7:∆Q7
→0
Q8:∆Q8
→0
Q9:∆Q9
→0
Q10:∆Q10
→0
NOTYET:'QUIZ ';∆N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇R←W ∆IS A
⍝ IS THE ANSWER A THE WORD W? AT A QUAD PROMPT THE WORDS GO AND
⍝ STOP ARE THE VARIABLES OF THOSE NAMES, WHICH HOLD THEMSELVES.
R←((⍴,W)=⍴,A)∧∧/(,W)=(⍴,W)↑,A
∇
∇∆TRY
'(TRY IT. TYPE GO TO GO ON, OR STOP TO LEAVE.)'
∇
∇R←∆PAUSE;∆A
⍝ THE PAUSE BETWEEN SECTIONS. WHAT THE READER TYPES IS READ WITH
⍝ QUAD AND PRINTED, UNTIL GO OR STOP. R IS 1 FOR STOP.
L:∆A←⎕
R←'STOP' ∆IS ∆A
→R/0
→('GO' ∆IS ∆A)/0
∆A
→L
∇
∇R←∆READ
⍝ READ A QUIZ ANSWER AS APL. THE QUESTION IS PRINTED BY THE CALLER.
R←⎕
∇
∇R←W ∆CHECK A
⍝ IS THE ANSWER A THE WANTED VALUE W? SAME COUNT, SAME VALUES,
⍝ AND THE SAME RANK; A SCALAR FOR A ONE-ELEMENT VECTOR PASSES
⍝ WITH A REMARK. R IS 1 FOR RIGHT.
R←0
→((×/⍴,W)≠×/⍴,A)/WRONG
→(~∧/,(,W)=,A)/WRONG
→((⍴⍴W)=⍴⍴A)/RIGHT
'RIGHT VALUE, THOUGH ONE IS A SCALAR AND ONE A VECTOR.'
R←1
→0
RIGHT:'RIGHT.'
R←1
→0
WRONG:'NO. THE ANSWER IS:'
W
∇
∇∆L1;∆Q
'LESSON 1: WHERE YOU ARE'
''
'THE SIX SPACES YOU TYPE AFTER ARE THE PROMPT. APL WAITS'
'THERE. WHAT YOU TYPE IS INDENTED; WHAT APL ANSWERS STARTS'
'AT THE LEFT MARGIN. TRY:'
''
'      2+2'
'      3×4'
''
'IT ANSWERS AT ONCE. THERE IS NO PROGRAM TO WRITE FIRST.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A LINE THAT BEGINS WITH A RIGHT PARENTHESIS IS NOT APL BUT'
'A SYSTEM COMMAND: A WORD TO THE SYSTEM AROUND APL. TWO OF'
'THEM SAY WHERE YOU ARE. TRY:'
''
'      )DIALECT'
'      )WSID'
''
'THE FIRST ANSWERS (A) ''70 OR (B) ''75. SW-APL HAS TWO MODES,'
'ONE MODELLED ON THE APL OF 1970 AND ONE ON THE APL OF 1975.'
'THIS COURSE RUNS IN BOTH; LESSON 16 SAYS HOW THEY DIFFER.'
'THE SECOND ANSWERS COURSE, THE NAME OF THIS WORKSPACE: THE'
'FUNCTIONS AND VARIABLES YOU ARE WORKING WITH.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WORKSPACES ARE KEPT IN NUMBERED LIBRARIES. TRY:'
''
'      )LIBS'
'      )LIB 2'
''
'LIBRARY 0 IS YOURS, WHERE )SAVE WRITES. LIBRARY 1 IS WHAT'
'SW-APL SHIPS. LIBRARY 2 IS THIS COURSE AND ITS COMPANIONS.'
')LIB N LISTS A LIBRARY AND )LOAD N NAME LOADS ONE, WHICH IS'
'HOW YOU GOT HERE. LESSON 15 IS ABOUT WORKSPACES.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WHEN YOU DO NOT KNOW WHAT TO TYPE, ASK. TRY:'
''
'      )HELP'
'      )HELP LIBS'
''
'THE FIRST LISTS THE SYSTEM COMMANDS, AND SAYS WHICH ARE'
'SW-APL''S OWN AND WHICH ARE HISTORICAL. THE SECOND EXPLAINS'
'ONE. )HELP, )LIBS AND )DIALECT ARE SW-APL''S; THE REST IS'
'WHAT THE ORIGINAL SYSTEMS HAD.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THIS IS HOW A LESSON WORKS: A FEW LINES, SOMETHING TO TRY,'
'AND A PAUSE. AT THE PAUSE THE PROMPT IS A QUAD AND A COLON,'
'AND ANY EXPRESSION OR SYSTEM COMMAND YOU TYPE IS RUN AND'
'ITS ANSWER PRINTED. GO GOES ON, STOP LEAVES. A MISTAKE IS'
'REPORTED AND THE PROMPT COMES BACK, SO TRY FREELY.'
''
'NEXT TAKES YOU TO THE LESSON AFTER THE LAST ONE YOU READ,'
'CONTENTS LISTS THEM ALL, AND LESSON N GOES TO ANY ONE.'
'EACH LESSON ENDS WITH A QUIZ: A QUESTION, THE QUAD PROMPT,'
'AND YOUR ANSWER AS APL, A NUMBER OR AN EXPRESSION THAT'
'MAKES ONE. STOP LEAVES A QUIZ TOO.'
''
'END OF LESSON 1. TYPE QUIZ 1 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q1;∆S;∆A
∆S←0
'WHAT DOES 2+2 GIVE? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+4 ∆CHECK ∆A
'WHICH LIBRARY IS YOURS, WHERE )SAVE WRITES?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHICH LIBRARY HOLDS THIS COURSE?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'HOW MANY LESSONS ARE THERE?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+16 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 4.'
∇
∇∆L2;∆Q
'LESSON 2: NUMBERS'
''
'THE FOUR ARITHMETIC FUNCTIONS ARE + - × AND ÷. TRY:'
''
'      7÷2'
'      2×3+4'
'      (2×3)+4'
''
'DIVISION GIVES 3.5, NOT 3: A NUMBER IS A NUMBER. AND 2×3+4'
'IS 14, NOT 10. APL READS A LINE FROM THE RIGHT: 3+4 FIRST,'
'THEN 2× THAT. THERE IS NO PRECEDENCE AMONG FUNCTIONS; ONLY'
'PARENTHESES CHANGE THE ORDER.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A NEGATIVE NUMBER IS WRITTEN WITH A HIGH MINUS, ¯, WHICH IS'
'PART OF THE NUMBER LIKE A DIGIT. THE MINUS SIGN, -, IS A'
'FUNCTION. TRY:'
''
'      ¯3+5'
'      2-3'
'      -5'
''
'EVERY ARITHMETIC FUNCTION HAS A ONE-ARGUMENT FORM TOO:'
'-5 IS NEGATIVE FIVE, ÷4 IS ONE QUARTER, ×¯7 0 7 IS THE'
'SIGN OF EACH, AND |¯7 IS THE MAGNITUDE, 7.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⌈ AND ⌊ ARE MAXIMUM AND MINIMUM WITH TWO ARGUMENTS, AND'
'CEILING AND FLOOR WITH ONE. TRY:'
''
'      3⌈5'
'      ⌈2.4'
'      ⌊2.4'
''
'| WITH TWO ARGUMENTS IS THE REMAINDER, THE LEFT ONE BEING'
'THE DIVISOR: 3|17 IS 2.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'* IS POWER, AND ALONE IT IS E TO THE POWER: *1 IS'
'2.718281828. ⍟ IS LOGARITHM, NATURAL ALONE AND TO A BASE'
'WITH TWO: 10⍟100 IS 2. ○1 IS PI, AND 1○X IS THE SINE OF X.'
'! IS FACTORIAL, AND 2!5 IS THE NUMBER OF WAYS TO CHOOSE 2'
'FROM 5, WHICH IS 10. TRY:'
''
'      2*10'
'      2*0.5'
'      !5'
''
'END OF LESSON 2. TYPE QUIZ 2 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q2;∆S;∆A
∆S←0
'WHAT IS 2×3+4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+14 ∆CHECK ∆A
'WHAT IS ¯3+5?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'WHAT IS 3|17, THE REMAINDER OF 17 DIVIDED BY 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'WHAT IS ⌈2.4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'WHAT IS 2*10?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1024 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L3;∆Q
'LESSON 3: VECTORS'
''
'NUMBERS TYPED IN A ROW MAKE A VECTOR, AND A FUNCTION WORKS'
'ON EVERY ELEMENT AT ONCE. TRY:'
''
'      1 2 3+4 5 6'
'      1 2 3×2'
''
'THE FIRST ADDS ELEMENT TO ELEMENT. THE SECOND MULTIPLIES'
'EVERY ELEMENT BY 2: A SINGLE NUMBER STRETCHES TO FIT.'
'TWO VECTORS OF DIFFERENT LENGTHS DO NOT FIT, AND THAT IS A'
'LENGTH ERROR.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⍳N IS THE FIRST N COUNTING NUMBERS, AND ⍴V IS HOW MANY'
'ELEMENTS V HAS. TRY:'
''
'      ⍳5'
'      2×⍳5'
'      ⍴3 4 5 6 7'
''
'⍳ IS THE INDEX GENERATOR AND ⍴ IS RHO, THE SHAPE. MUCH OF'
'APL IS BUILT FROM THESE TWO.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WITH TWO ARGUMENTS ⍴ IS RESHAPE: N⍴V IS N ELEMENTS TAKEN'
'FROM V, CYCLING ROUND WHEN V RUNS OUT. THE COMMA JOINS TWO'
'VECTORS. TRY:'
''
'      5⍴1 2'
'      2⍴7'
'      1 2,3 4'
''
'A COMMA ALONE MAKES A VECTOR OF ANYTHING: ,7 IS A VECTOR'
'OF ONE ELEMENT, WHICH IS NOT THE SAME AS THE NUMBER 7.'
'⍴7 IS EMPTY, SINCE A LONE NUMBER HAS NO LENGTH, BUT ⍴,7'
'IS 1.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A VECTOR MAY HAVE NO ELEMENTS AT ALL. ⍳0 IS ONE, AND SO IS'
'0⍴5. IT PRINTS AS AN EMPTY LINE. TRY:'
''
'      ⍳0'
'      ⍴⍳0'
''
'EMPTY VECTORS ARE NOT A CURIOSITY: A FUNCTION THAT WORKS'
'ON A VECTOR OF ANY LENGTH WORKS ON ONE OF LENGTH ZERO,'
'AND THAT IS WHAT MAKES THE END OF A LIST NO SPECIAL CASE.'
''
'END OF LESSON 3. TYPE QUIZ 3 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q3;∆S;∆A
∆S←0
'WHAT IS ⍳4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 3 4 ∆CHECK ∆A
'HOW MANY ELEMENTS HAS 3 4 5 6 7? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 ∆CHECK ∆A
'WHAT IS 2 3 4×2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+4 6 8 ∆CHECK ∆A
'WHAT IS 5⍴1 2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 1 2 1 ∆CHECK ∆A
'WHAT IS 1 2,3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 3 4 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L4;∆Q
'LESSON 4: COMPARISON AND LOGIC'
''
'< ≤ = ≥ > AND ≠ COMPARE, AND ANSWER 1 FOR TRUE AND 0 FOR'
'FALSE. ON A VECTOR THEY ANSWER FOR EVERY ELEMENT. TRY:'
''
'      3<5'
'      1 2 3=2'
'      1 2 3>2'
''
'CHARACTERS COMPARE TOO: ''ABC''=''B'' IS 0 1 0.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'∧ IS AND, ∨ IS OR, AND ~ IS NOT. THEY WORK ON 1 AND 0. TRY:'
''
'      1∧0'
'      1∨0'
'      ~1 0 1'
''
'≠ ON 1 AND 0 IS EXCLUSIVE OR: 1≠1 0 IS 0 1. ⍲ AND ⍱ ARE'
'NAND AND NOR, THE TWO NEGATED.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'1 AND 0 ARE NUMBERS, NOT A SEPARATE KIND OF VALUE. SO A'
'COMPARISON CAN BE USED IN ARITHMETIC. TRY:'
''
'      2×1 2 3>1'
'      (1 2 3>1)×10 20 30'
''
'MULTIPLYING BY A COMPARISON KEEPS THE ELEMENTS THAT PASS'
'AND ZEROES THE REST. THE NEXT LESSON COUNTS THEM.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⌈ AND ⌊ FROM LESSON 2 ARE COMPARISONS OF A KIND: 3⌈5 IS'
'THE LARGER. ON 1 AND 0, ⌈ IS OR AND ⌊ IS AND. TRY:'
''
'      1⌈0'
'      1⌊0'
'      3 1 4⌈2'
''
'END OF LESSON 4. TYPE QUIZ 4 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q4;∆S;∆A
∆S←0
'WHAT IS 1 2 3>2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 0 1 ∆CHECK ∆A
'WHAT IS 1∧0?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHAT IS ~1 0 1?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 1 0 ∆CHECK ∆A
'WHAT IS 3≠3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHAT IS (1 2 3>1)×10 20 30?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 20 30 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L5;∆Q
'LESSON 5: REDUCTION AND SCAN'
''
'F/V PUTS THE FUNCTION F BETWEEN THE ELEMENTS OF V. +/ IS'
'THE SUM, ×/ THE PRODUCT, ⌈/ THE LARGEST, ⌊/ THE SMALLEST.'
'TRY:'
''
'      +/1 2 3 4'
'      ×/2 3 4'
'      ⌈/3 9 2'
''
'THIS IS REDUCTION, AND / IS AN OPERATOR: IT TAKES A'
'FUNCTION AND MAKES A NEW ONE. -/1 2 3 IS 1-2-3 READ FROM'
'THE RIGHT, 1-(2-3), WHICH IS 2.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'ON 1 AND 0, ∧/ ASKS WHETHER ALL ARE 1 AND ∨/ WHETHER ANY'
'IS. +/ COUNTS THEM. TRY:'
''
'      ∧/1 1 0'
'      ∨/1 2 3>2'
'      +/2 4 6 8>3'
''
'THE LAST COUNTS HOW MANY ELEMENTS EXCEED 3. NO LOOP WAS'
'WRITTEN: THE COMPARISON MADE A VECTOR OF 1S AND 0S, AND'
'THE REDUCTION SUMMED IT.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'F\V IS SCAN: EVERY REDUCTION ALONG THE WAY. +\ IS THE'
'RUNNING TOTAL. TRY:'
''
'      +\1 2 3 4'
'      ×\1 2 3 4'
'      ⌈\3 1 4 1 5'
''
'×\⍳N IS THE FACTORIALS, AND ⌈\ IS THE LARGEST SO FAR.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THE AVERAGE OF A VECTOR IS ITS SUM OVER ITS LENGTH:'
''
'      (+/2 4 6)÷⍴2 4 6'
''
'REDUCING AN EMPTY VECTOR GIVES THE VALUE THAT LEAVES THE'
'FUNCTION ALONE: +/⍳0 IS 0 AND ×/⍳0 IS 1. SO THE SUM OF'
'NOTHING IS 0, AS IT SHOULD BE, AND NO CASE IS SPECIAL.'
''
'END OF LESSON 5. TYPE QUIZ 5 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q5;∆S;∆A
∆S←0
'WHAT IS +/1 2 3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+10 ∆CHECK ∆A
'WHAT IS ×/2 3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+24 ∆CHECK ∆A
'WHAT IS +\1 2 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 3 6 ∆CHECK ∆A
'WHAT IS ⌈/3 9 2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+9 ∆CHECK ∆A
'HOW MANY OF 2 4 6 8 EXCEED 3? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L6;∆Q
'LESSON 6: SELECTION'
''
'BRACKETS AFTER A VECTOR PICK ELEMENTS BY POSITION, COUNTING'
'FROM 1. THE INDEX MAY BE A VECTOR TOO. TRY:'
''
'      V←10 20 30 40'
'      V[3]'
'      V[1 3]'
'      V[4 3 2 1]'
''
'THE ARROW, ←, GIVES V ITS VALUE, AND V KEEPS IT UNTIL YOU'
'CHANGE IT. A LINE THAT ONLY ASSIGNS PRINTS NOTHING. AN'
'INDEXED NAME ON THE LEFT OF THE ARROW CHANGES ONE ELEMENT:'
'V[2]←25, AND THEN V.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'↑ TAKES THE FIRST N ELEMENTS AND ↓ DROPS THEM; A NEGATIVE'
'N COUNTS FROM THE END. TRY:'
''
'      2↑V'
'      ¯1↑V'
'      1↓V'
'      ¯2↓V'
''
'⌽ REVERSES, AND N⌽V ROTATES BY N: 1⌽V MOVES THE FIRST'
'ELEMENT TO THE END.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A VECTOR OF 1S AND 0S ON THE LEFT OF / SELECTS: THIS IS'
'COMPRESSION, AND WITH A COMPARISON IT IS HOW APL FILTERS.'
'TRY:'
''
'      (V>15)/V'
'      1 0 1 1/V'
'      1 0 1 1\1 2 3'
''
'THE LAST IS EXPANSION: THE 0 OPENS A GAP, FILLED WITH 0.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'∊ ASKS WHETHER EACH ELEMENT ON THE LEFT IS SOMEWHERE ON'
'THE RIGHT, AND V⍳X ASKS WHERE: THE POSITION OF X IN V, OR'
'ONE PAST THE END IF IT IS NOT THERE. TRY:'
''
'      30∊V'
'      V⍳30'
'      V⍳99'
''
'END OF LESSON 6. TYPE QUIZ 6 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q6;∆S;∆A
∆S←0
'WHAT IS 2↑5 6 7 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 6 ∆CHECK ∆A
'WHAT IS 1↓5 6 7 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+6 7 8 ∆CHECK ∆A
'WHAT IS ⌽1 2 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 2 1 ∆CHECK ∆A
'WHAT IS 1 0 1/7 8 9?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+7 9 ∆CHECK ∆A
'WHAT IS 7 8 9⍳8, THE POSITION OF 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L7;∆Q
'LESSON 7: MATRICES'
''
'RESHAPE WITH TWO NUMBERS ON THE LEFT MAKES A MATRIX: ROWS'
'BY COLUMNS, FILLED ROW BY ROW. TRY:'
''
'      M←3 4⍴⍳12'
'      M'
'      ⍴M'
'      ⍴⍴M'
''
'⍴M IS 3 4, BOTH DIMENSIONS. ⍴⍴M IS 2, THE NUMBER OF'
'DIMENSIONS, CALLED THE RANK: A NUMBER HAS RANK 0, A VECTOR'
'1, A MATRIX 2, AND APL GOES ON UPWARDS.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'INDEXING A MATRIX TAKES TWO SUBSCRIPTS, ROW THEN COLUMN,'
'WITH A SEMICOLON BETWEEN. LEAVE ONE OUT TO TAKE ALL OF IT.'
'TRY:'
''
'      M[2;3]'
'      M[2;]'
'      M[;3]'
'      M[1 3;2 4]'
''
'THE LAST PICKS ROWS 1 AND 3 AND COLUMNS 2 AND 4, AND IS A'
'MATRIX OF ITS OWN.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⍉M IS THE TRANSPOSE, ROWS FOR COLUMNS. A REDUCTION ON A'
'MATRIX RUNS ALONG THE LAST DIMENSION, THE ROWS, AND THE'
'BARRED FORM ⌿ RUNS DOWN THE COLUMNS. TRY:'
''
'      ⍉M'
'      +/M'
'      +⌿M'
'      +/[1]M'
''
'THE BRACKETED NUMBER NAMES THE AXIS: +/[1]M IS +⌿M.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THE SCALAR FUNCTIONS WORK ON A MATRIX AS ON A VECTOR,'
'ELEMENT BY ELEMENT, AND THE COMMA RAVELS IT BACK INTO A'
'VECTOR. TRY:'
''
'      M×2'
'      M>6'
'      ,M'
'      2 3⍴''ABCDEF'''
''
'A MATRIX PRINTS WITH ITS COLUMNS LINED UP, NUMBERS TO THE'
'RIGHT AND CHARACTERS TO THE LEFT.'
''
'END OF LESSON 7. TYPE QUIZ 7 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q7;∆S;∆A
∆S←0
'WHAT IS ⍴2 3⍴⍳6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 3 ∆CHECK ∆A
'WHAT IS (2 3⍴⍳6)[2;1]?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+4 ∆CHECK ∆A
'WHAT IS +/2 3⍴⍳6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+6 15 ∆CHECK ∆A
'WHAT IS +⌿2 3⍴⍳6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 7 9 ∆CHECK ∆A
'WHAT IS ⍴⍉2 3⍴⍳6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 2 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L8;∆Q
'LESSON 8: PRODUCTS'
''
'THE OUTER PRODUCT, ∘.F, APPLIES F TO EVERY PAIR: EACH'
'ELEMENT ON THE LEFT AGAINST EACH ON THE RIGHT, MAKING A'
'TABLE. TRY:'
''
'      1 2 3∘.×1 2 3'
'      (⍳3)∘.+⍳3'
'      (⍳5)∘.×⍳5'
''
'THE LAST IS THE MULTIPLICATION TABLE, IN ONE EXPRESSION.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WITH A COMPARISON THE OUTER PRODUCT MAKES A TABLE OF 1S AND'
'0S, WHICH IS OFTEN A SHAPE YOU WANT. TRY:'
''
'      (⍳3)∘.=⍳3'
'      (⍳4)∘.≥⍳4'
''
'THE FIRST IS THE IDENTITY MATRIX; THE SECOND A TRIANGLE.'
'LESSON 9 COUNTS WITH ONE.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THE INNER PRODUCT F.G COMBINES TWO FUNCTIONS: G BETWEEN'
'THE PAIRS, THEN F REDUCING. +.× IS THE SUM OF PRODUCTS, AND'
'ON MATRICES IT IS THE MATRIX PRODUCT. TRY:'
''
'      1 2 3+.×4 5 6'
'      (2 3⍴⍳6)+.×3 2⍴⍳6'
''
'THE FIRST IS 4+10+18, WHICH IS 32. THE SECOND IS 2 BY 2:'
'EACH ROW OF THE LEFT AGAINST EACH COLUMN OF THE RIGHT.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'ANY TWO FUNCTIONS WILL DO. ∧.= ASKS WHETHER TWO VECTORS'
'AGREE THROUGHOUT, AND +.= COUNTS WHERE THEY AGREE. TRY:'
''
'      ''ABC''∧.=''ABC'''
'      ''ABC''∧.=''ABD'''
'      1 2 3+.=1 5 3'
''
'END OF LESSON 8. TYPE QUIZ 8 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q8;∆S;∆A
∆S←0
'WHAT IS 1 2 3+.×4 5 6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+32 ∆CHECK ∆A
'WHAT IS ⍴(⍳2)∘.+⍳3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 3 ∆CHECK ∆A
'IN (⍳3)∘.×⍳3, WHAT IS THE ELEMENT IN ROW 2, COLUMN 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+6 ∆CHECK ∆A
'WHAT IS ''AB''∧.=''AB''?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 ∆CHECK ∆A
'WHAT IS 1 2+.=1 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L9;∆Q
'LESSON 9: ORDER AND COUNTING'
''
'⍋V IS GRADE UP: NOT THE SORTED VECTOR, BUT THE POSITIONS'
'THAT WOULD SORT IT. INDEXING BY IT DOES THE SORTING. TRY:'
''
'      ⍋3 1 2'
'      V←31 4 15 9'
'      V[⍋V]'
'      V[⍒V]'
''
'⍒ IS GRADE DOWN. THE GRADE IS MORE USEFUL THAN A SORT: IT'
'CAN ORDER A SECOND VECTOR THE SAME WAY, NAMES BY SCORES.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'?N IS A NUMBER FROM 1 TO N, DIFFERENT EACH TIME, AND M?N IS'
'M DIFFERENT ONES: A ROLL, AND A DEAL. TRY:'
''
'      ?6'
'      ?6 6'
'      5?10'
''
'THE SEQUENCE STARTS FROM THE SAME PLACE IN EVERY CLEAR'
'WORKSPACE, SO A PROGRAM USING ? CAN BE RUN AGAIN EXACTLY.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⊤ AND ⊥ ARE ENCODE AND DECODE, BETWEEN A NUMBER AND ITS'
'DIGITS IN ANY BASE, OR MIXED BASES. TRY:'
''
'      2 2 2 2⊤13'
'      2⊥1 1 0 1'
'      10⊥1 9 8 4'
'      24 60 60⊤3661'
''
'THE LAST TURNS SECONDS INTO HOURS, MINUTES AND SECONDS.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'TO COUNT HOW OFTEN EACH VALUE OCCURS, COMPARE THE VALUES'
'AGAINST THE DATA WITH AN OUTER PRODUCT AND SUM THE ROWS.'
'A TABLE OF 1S AND 0S INDEXED INTO TWO CHARACTERS IS A'
'PICTURE. TRY:'
''
'      C←+/(⍳3)∘.=1 3 2 3 3 1'
'      C'
'      '' *''[1+C∘.≥⍳3]'
''
'END OF LESSON 9. TYPE QUIZ 9 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q9;∆S;∆A
∆S←0
'WHAT IS ⍋3 1 2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 3 1 ∆CHECK ∆A
'WHAT IS 5 2 8 SORTED INTO ASCENDING ORDER?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 5 8 ∆CHECK ∆A
'WHAT IS 2⊥1 0 1?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 ∆CHECK ∆A
'WHAT IS 2 2 2⊤6?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 1 0 ∆CHECK ∆A
'HOW OFTEN DO 1 AND 2 EACH OCCUR IN 1 2 2 1 2? TWO NUMBERS.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 3 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L10;∆Q
'LESSON 10: CHARACTERS'
''
'CHARACTERS GO IN QUOTES, AND A ROW OF THEM IS A VECTOR LIKE'
'ANY OTHER. A QUOTE INSIDE IS DOUBLED. TRY:'
''
'      ''HELLO'''
'      ⍴''HELLO'''
'      ''IT''''S'''
'      ''ABC'',''DEF'''
''
'''A'' IS A SINGLE CHARACTER, A SCALAR, AND ⍴''A'' IS EMPTY AS'
'⍴7 WAS; ,''A'' IS A VECTOR OF ONE.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'COMPARISON, MEMBERSHIP, INDEX-OF, COMPRESSION AND REVERSAL'
'ALL WORK ON CHARACTERS. TRY:'
''
'      ''HELLO''=''L'''
'      ''HELLO''⍳''L'''
'      ''HELLO''∊''AEIOU'''
'      (~''HELLO''∊''AEIOU'')/''HELLO'''
'      ⌽''HELLO'''
''
'THE FOURTH KEEPS THE CONSONANTS: THE VOWELS ARE FOUND BY'
'MEMBERSHIP, NEGATED, AND USED TO COMPRESS.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A MATRIX OF CHARACTERS IS A LIST OF WORDS, ONE TO A ROW,'
'PADDED WITH BLANKS TO THE LONGEST. TRY:'
''
'      NAMES←3 4⍴''ANN BOB CARL'''
'      NAMES'
'      NAMES[2;]'
'      2 5⍴''HELLOWORLD'''
''
'NAMES[2;] IS THE SECOND WORD, BLANK AND ALL.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'CHARACTERS AND NUMBERS CANNOT BE JOINED WITH A COMMA: THAT'
'IS A DOMAIN ERROR. TO PRINT THEM ON ONE LINE, SEPARATE THEM'
'WITH SEMICOLONS. TRY:'
''
'      ''TOTAL: '';+/1 2 3'
'      ''X IS '';5;'' AND Y IS '';6'
''
'THIS IS MIXED OUTPUT, AND IT IS HOW THIS COURSE PRINTS YOUR'
'SCORE.'
''
'END OF LESSON 10. TYPE QUIZ 10 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q10;∆S;∆A
∆S←0
'HOW MANY CHARACTERS ARE IN ''APL''? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'WHAT IS ''BANANA''⍳''N''?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'HOW MANY TIMES DOES A OCCUR IN ''BANANA''?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'WHAT IS ⌽''APL''? TYPE IT IN QUOTES.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+'LPA' ∆CHECK ∆A
'WHAT IS ''ABC''∊''CAT''?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 0 1 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
