⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 15.30.00 09/24/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID COURSE
LAST←0
STOP←'STOP'
∇DESCRIBE
'COURSE -- APL, LESSON BY LESSON, WITH QUIZZES.'
''
'   START       BEGIN AT LESSON 1.'
'   CONTENTS    THE LESSONS, BY NUMBER AND TITLE.'
'   LESSON N    READ LESSON N.'
'   NEXT        THE LESSON AFTER THE LAST ONE YOU READ.'
'   QUIZ N      QUESTIONS ON LESSON N, MARKED AS YOU GO.'
''
'A LESSON PAUSES BETWEEN SECTIONS SO YOU CAN TRY WHAT IT'
'SHOWS. PRESS RETURN TO GO ON. TYPE STOP AT ANY PROMPT TO'
'LEAVE A LESSON OR A QUIZ.'
∇
∇CONTENTS
'THE LESSONS. LESSON N READS ONE; QUIZ N ASKS ABOUT IT.'
''
'   1  WHERE YOU ARE'
'   2  NUMBERS'
'   3  VECTORS'
'   4  COMPARISON AND LOGIC'
'   5  REDUCTION AND SCAN'
'   6  SELECTION'
'   7  MATRICES'
'   8  PRODUCTS'
'   9  ORDER AND COUNTING'
'  10  CHARACTERS'
'  11  DEFINING FUNCTIONS'
'  12  BRANCHING'
'  13  INPUT AND OUTPUT'
'  14  ERRORS'
'  15  WORKSPACES'
'  16  THE TWO MODES'
∇
∇START
LESSON 1
∇
∇NEXT
→(LAST≥16)/END
LESSON LAST+1
→0
END:'THAT WAS THE LAST LESSON. CONTENTS LISTS THEM ALL.'
∇
∇LESSON N
⍝ LAST IS GLOBAL ON PURPOSE: NEXT READS IT, AND )SAVE KEEPS IT.
→((N<1)∨N>16)/BAD
LAST←N
→(N>1)/NOTYET
∆L1
→0
NOTYET:'LESSON ';N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇QUIZ N
→((N<1)∨N>16)/BAD
→(N>1)/NOTYET
'QUIZ ';N;'. TYPE EACH ANSWER AS APL AFTER THE QUAD PROMPT.'
∆Q1
→0
NOTYET:'QUIZ ';N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇R←∆PAUSE;A
⍝ THE PAUSE BETWEEN SECTIONS. 1 MEANS THE READER TYPED STOP.
⍞←'(RETURN TO GO ON, OR STOP) '
A←⍞
R←∆STOPPED A
∇
∇R←∆STOPPED A
⍝ WAS THE ANSWER A THE WORD STOP? AT A QUAD PROMPT, STOP IS THE
⍝ VARIABLE OF THAT NAME; AT A QUOTE-QUAD PROMPT, THE WORD ITSELF.
R←(4=⍴,A)∧∧/'STOP'=4↑,A
∇
∇R←∆ASK T
⍝ PRINT THE QUESTION T AND READ THE ANSWER AS APL.
T
R←⎕
∇
∇R←W ∆CHECK A
⍝ IS THE ANSWER A THE WANTED VALUE W? SAME COUNT, SAME VALUES,
⍝ AND THE SAME RANK; A SCALAR FOR A ONE-ELEMENT VECTOR PASSES
⍝ WITH A REMARK. R IS 1 FOR RIGHT.
R←0
→((×/⍴,W)≠×/⍴,A)/WRONG
→(~∧/,(,W)=,A)/WRONG
→((⍴⍴W)=⍴⍴A)/RIGHT
'RIGHT VALUE, THOUGH ONE IS A SCALAR AND ONE A VECTOR.'
R←1
→0
RIGHT:'RIGHT.'
R←1
→0
WRONG:'NO. THE ANSWER IS:'
W
∇
∇∆L1;Q
'LESSON 1: WHERE YOU ARE'
''
'THE SIX SPACES YOU TYPE AFTER ARE THE PROMPT. APL WAITS'
'THERE. WHAT YOU TYPE IS INDENTED; WHAT APL ANSWERS STARTS'
'AT THE LEFT MARGIN. TRY:'
''
'      2+2'
'      3×4'
''
'IT ANSWERS AT ONCE. THERE IS NO PROGRAM TO WRITE FIRST.'
Q←∆PAUSE
→Q/0
'A LINE THAT BEGINS WITH A RIGHT PARENTHESIS IS NOT APL BUT'
'A SYSTEM COMMAND: A WORD TO THE SYSTEM AROUND APL. TWO OF'
'THEM SAY WHERE YOU ARE. TRY:'
''
'      )DIALECT'
'      )WSID'
''
'THE FIRST ANSWERS (A) ''70 OR (B) ''75. SW-APL HAS TWO MODES,'
'ONE MODELLED ON THE APL OF 1970 AND ONE ON THE APL OF 1975.'
'THIS COURSE RUNS IN BOTH; LESSON 16 SAYS HOW THEY DIFFER.'
'THE SECOND ANSWERS COURSE, THE NAME OF THIS WORKSPACE: THE'
'FUNCTIONS AND VARIABLES YOU ARE WORKING WITH.'
Q←∆PAUSE
→Q/0
'WORKSPACES ARE KEPT IN NUMBERED LIBRARIES. TRY:'
''
'      )LIBS'
'      )LIB 2'
''
'LIBRARY 0 IS YOURS, WHERE )SAVE WRITES. LIBRARY 1 IS WHAT'
'SW-APL SHIPS. LIBRARY 2 IS THIS COURSE AND ITS COMPANIONS.'
')LIB N LISTS A LIBRARY AND )LOAD N NAME LOADS ONE, WHICH IS'
'HOW YOU GOT HERE. LESSON 15 IS ABOUT WORKSPACES.'
Q←∆PAUSE
→Q/0
'WHEN YOU DO NOT KNOW WHAT TO TYPE, ASK. TRY:'
''
'      )HELP'
'      )HELP LIBS'
''
'THE FIRST LISTS THE SYSTEM COMMANDS, AND SAYS WHICH ARE'
'SW-APL''S OWN AND WHICH ARE HISTORICAL. THE SECOND EXPLAINS'
'ONE. )HELP, )LIBS AND )DIALECT ARE SW-APL''S; THE REST IS'
'WHAT THE ORIGINAL SYSTEMS HAD.'
Q←∆PAUSE
→Q/0
'THIS IS HOW A LESSON WORKS: A FEW LINES, SOMETHING TO TRY,'
'AND A PAUSE. PRESS RETURN TO GO ON, OR TYPE STOP TO LEAVE.'
'NEXT TAKES YOU TO THE LESSON AFTER THE LAST ONE YOU READ,'
'CONTENTS LISTS THEM ALL, AND LESSON N GOES TO ANY ONE.'
''
'EACH LESSON ENDS WITH A QUIZ. A QUESTION IS ASKED, A PROMPT'
'OF A QUAD AND A COLON IS PRINTED, AND YOU TYPE THE ANSWER'
'AS APL: A NUMBER, OR AN EXPRESSION THAT MAKES ONE. STOP'
'LEAVES A QUIZ TOO.'
''
'END OF LESSON 1. TYPE QUIZ 1 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q1;S;A
S←0
A←∆ASK 'WHAT DOES 2+2 GIVE? TYPE THE NUMBER.'
→(∆STOPPED A)/0
S←S+4 ∆CHECK A
A←∆ASK 'WHICH LIBRARY IS YOURS, WHERE )SAVE WRITES?'
→(∆STOPPED A)/0
S←S+0 ∆CHECK A
A←∆ASK 'WHICH LIBRARY HOLDS THIS COURSE?'
→(∆STOPPED A)/0
S←S+2 ∆CHECK A
A←∆ASK 'HOW MANY LESSONS ARE THERE?'
→(∆STOPPED A)/0
S←S+16 ∆CHECK A
'YOU GOT ';S;' OF 4.'
∇
