⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 16.30.00 09/24/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID COURSE
GO←'GO'
LAST←0
STOP←'STOP'
∇DESCRIBE
'COURSE -- APL, LESSON BY LESSON, WITH QUIZZES.'
''
'   START       BEGIN AT LESSON 1.'
'   CONTENTS    THE LESSONS, BY NUMBER AND TITLE.'
'   LESSON N    READ LESSON N.'
'   NEXT        THE LESSON AFTER THE LAST ONE YOU READ.'
'   QUIZ N      QUESTIONS ON LESSON N, MARKED AS YOU GO.'
''
'A LESSON PAUSES BETWEEN SECTIONS SO YOU CAN TRY WHAT IT'
'SHOWS. AT A PAUSE, TYPE AN EXPRESSION TO SEE ITS VALUE,'
'GO TO GO ON, OR STOP TO LEAVE A LESSON OR A QUIZ.'
∇
∇CONTENTS
'THE LESSONS. LESSON N READS ONE; QUIZ N ASKS ABOUT IT.'
''
'   1  WHERE YOU ARE'
'   2  NUMBERS'
'   3  VECTORS'
'   4  COMPARISON AND LOGIC'
'   5  REDUCTION AND SCAN'
'   6  SELECTION'
'   7  MATRICES'
'   8  PRODUCTS'
'   9  ORDER AND COUNTING'
'  10  CHARACTERS'
'  11  DEFINING FUNCTIONS'
'  12  BRANCHING'
'  13  INPUT AND OUTPUT'
'  14  ERRORS'
'  15  WORKSPACES'
'  16  THE TWO MODES'
∇
∇START
LESSON 1
∇
∇NEXT
→(LAST≥16)/END
LESSON LAST+1
→0
END:'THAT WAS THE LAST LESSON. CONTENTS LISTS THEM ALL.'
∇
∇LESSON ∆N
⍝ LAST IS GLOBAL ON PURPOSE: NEXT READS IT, AND )SAVE KEEPS IT.
⍝ THE LOCALS OF EVERYTHING ON THE WAY TO A PAUSE ARE DELTA NAMES,
⍝ SO THAT WHAT THE READER TYPES THERE SEES THEIR OWN NAMES.
→((∆N<1)∨∆N>16)/BAD
LAST←∆N
→(∆N>6)/NOTYET
→(L1,L2,L3,L4,L5,L6)[∆N]
L1:∆L1
→0
L2:∆L2
→0
L3:∆L3
→0
L4:∆L4
→0
L5:∆L5
→0
L6:∆L6
→0
NOTYET:'LESSON ';∆N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇QUIZ ∆N
→((∆N<1)∨∆N>16)/BAD
→(∆N>6)/NOTYET
'QUIZ ';∆N;'. TYPE EACH ANSWER AS APL AFTER THE QUAD PROMPT.'
→(Q1,Q2,Q3,Q4,Q5,Q6)[∆N]
Q1:∆Q1
→0
Q2:∆Q2
→0
Q3:∆Q3
→0
Q4:∆Q4
→0
Q5:∆Q5
→0
Q6:∆Q6
→0
NOTYET:'QUIZ ';∆N;' IS NOT YET WRITTEN.'
→0
BAD:'THERE ARE 16 LESSONS. TYPE CONTENTS TO SEE THEM.'
∇
∇R←W ∆IS A
⍝ IS THE ANSWER A THE WORD W? AT A QUAD PROMPT THE WORDS GO AND
⍝ STOP ARE THE VARIABLES OF THOSE NAMES, WHICH HOLD THEMSELVES.
R←((⍴,W)=⍴,A)∧∧/(,W)=(⍴,W)↑,A
∇
∇∆TRY
'(TRY IT. TYPE GO TO GO ON, OR STOP TO LEAVE.)'
∇
∇R←∆PAUSE;∆A
⍝ THE PAUSE BETWEEN SECTIONS. WHAT THE READER TYPES IS READ WITH
⍝ QUAD AND PRINTED, UNTIL GO OR STOP. R IS 1 FOR STOP.
L:∆A←⎕
R←'STOP' ∆IS ∆A
→R/0
→('GO' ∆IS ∆A)/0
∆A
→L
∇
∇R←∆READ
⍝ READ A QUIZ ANSWER AS APL. THE QUESTION IS PRINTED BY THE CALLER.
R←⎕
∇
∇R←W ∆CHECK A
⍝ IS THE ANSWER A THE WANTED VALUE W? SAME COUNT, SAME VALUES,
⍝ AND THE SAME RANK; A SCALAR FOR A ONE-ELEMENT VECTOR PASSES
⍝ WITH A REMARK. R IS 1 FOR RIGHT.
R←0
→((×/⍴,W)≠×/⍴,A)/WRONG
→(~∧/,(,W)=,A)/WRONG
→((⍴⍴W)=⍴⍴A)/RIGHT
'RIGHT VALUE, THOUGH ONE IS A SCALAR AND ONE A VECTOR.'
R←1
→0
RIGHT:'RIGHT.'
R←1
→0
WRONG:'NO. THE ANSWER IS:'
W
∇
∇∆L1;∆Q
'LESSON 1: WHERE YOU ARE'
''
'THE SIX SPACES YOU TYPE AFTER ARE THE PROMPT. APL WAITS'
'THERE. WHAT YOU TYPE IS INDENTED; WHAT APL ANSWERS STARTS'
'AT THE LEFT MARGIN. TRY:'
''
'      2+2'
'      3×4'
''
'IT ANSWERS AT ONCE. THERE IS NO PROGRAM TO WRITE FIRST.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A LINE THAT BEGINS WITH A RIGHT PARENTHESIS IS NOT APL BUT'
'A SYSTEM COMMAND: A WORD TO THE SYSTEM AROUND APL. TWO OF'
'THEM SAY WHERE YOU ARE. TRY THEM ONCE THIS LESSON IS OVER:'
''
'      )DIALECT'
'      )WSID'
''
'THE FIRST ANSWERS (A) ''70 OR (B) ''75. SW-APL HAS TWO MODES,'
'ONE MODELLED ON THE APL OF 1970 AND ONE ON THE APL OF 1975.'
'THIS COURSE RUNS IN BOTH; LESSON 16 SAYS HOW THEY DIFFER.'
'THE SECOND ANSWERS COURSE, THE NAME OF THIS WORKSPACE: THE'
'FUNCTIONS AND VARIABLES YOU ARE WORKING WITH.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WORKSPACES ARE KEPT IN NUMBERED LIBRARIES:'
''
'      )LIBS'
'      )LIB 2'
''
'LIBRARY 0 IS YOURS, WHERE )SAVE WRITES. LIBRARY 1 IS WHAT'
'SW-APL SHIPS. LIBRARY 2 IS THIS COURSE AND ITS COMPANIONS.'
')LIB N LISTS A LIBRARY AND )LOAD N NAME LOADS ONE, WHICH IS'
'HOW YOU GOT HERE. LESSON 15 IS ABOUT WORKSPACES.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WHEN YOU DO NOT KNOW WHAT TO TYPE, ASK:'
''
'      )HELP'
'      )HELP LIBS'
''
'THE FIRST LISTS THE SYSTEM COMMANDS, AND SAYS WHICH ARE'
'SW-APL''S OWN AND WHICH ARE HISTORICAL. THE SECOND EXPLAINS'
'ONE. )HELP, )LIBS AND )DIALECT ARE SW-APL''S; THE REST IS'
'WHAT THE ORIGINAL SYSTEMS HAD.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THIS IS HOW A LESSON WORKS: A FEW LINES, SOMETHING TO TRY,'
'AND A PAUSE. AT THE PAUSE THE PROMPT IS A QUAD AND A COLON,'
'AND ANY EXPRESSION YOU TYPE IS EVALUATED AND PRINTED. GO'
'GOES ON, STOP LEAVES. A SYSTEM COMMAND CANNOT BE TYPED'
'THERE, WHICH IS WHY THE ONES ABOVE WAIT FOR THE END.'
''
'IF WHAT YOU TYPE AT A PAUSE IS AN ERROR, THE LESSON STOPS'
'WITH THE REPORT. TYPE → ALONE TO CLEAR IT, THEN LESSON N'
'TO READ THE LESSON AGAIN. LESSON 14 EXPLAINS.'
''
'NEXT TAKES YOU TO THE LESSON AFTER THE LAST ONE YOU READ,'
'CONTENTS LISTS THEM ALL, AND LESSON N GOES TO ANY ONE.'
'EACH LESSON ENDS WITH A QUIZ: A QUESTION, THE QUAD PROMPT,'
'AND YOUR ANSWER AS APL, A NUMBER OR AN EXPRESSION THAT'
'MAKES ONE. STOP LEAVES A QUIZ TOO.'
''
'END OF LESSON 1. TYPE QUIZ 1 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q1;∆S;∆A
∆S←0
'WHAT DOES 2+2 GIVE? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+4 ∆CHECK ∆A
'WHICH LIBRARY IS YOURS, WHERE )SAVE WRITES?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHICH LIBRARY HOLDS THIS COURSE?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'HOW MANY LESSONS ARE THERE?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+16 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 4.'
∇
∇∆L2;∆Q
'LESSON 2: NUMBERS'
''
'THE FOUR ARITHMETIC FUNCTIONS ARE + - × AND ÷. TRY:'
''
'      7÷2'
'      2×3+4'
'      (2×3)+4'
''
'DIVISION GIVES 3.5, NOT 3: A NUMBER IS A NUMBER. AND 2×3+4'
'IS 14, NOT 10. APL READS A LINE FROM THE RIGHT: 3+4 FIRST,'
'THEN 2× THAT. THERE IS NO PRECEDENCE AMONG FUNCTIONS; ONLY'
'PARENTHESES CHANGE THE ORDER.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A NEGATIVE NUMBER IS WRITTEN WITH A HIGH MINUS, ¯, WHICH IS'
'PART OF THE NUMBER LIKE A DIGIT. THE MINUS SIGN, -, IS A'
'FUNCTION. TRY:'
''
'      ¯3+5'
'      2-3'
'      -5'
''
'EVERY ARITHMETIC FUNCTION HAS A ONE-ARGUMENT FORM TOO:'
'-5 IS NEGATIVE FIVE, ÷4 IS ONE QUARTER, ×¯7 0 7 IS THE'
'SIGN OF EACH, AND |¯7 IS THE MAGNITUDE, 7.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⌈ AND ⌊ ARE MAXIMUM AND MINIMUM WITH TWO ARGUMENTS, AND'
'CEILING AND FLOOR WITH ONE. TRY:'
''
'      3⌈5'
'      ⌈2.4'
'      ⌊2.4'
''
'| WITH TWO ARGUMENTS IS THE REMAINDER, THE LEFT ONE BEING'
'THE DIVISOR: 3|17 IS 2.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'* IS POWER, AND ALONE IT IS E TO THE POWER: *1 IS'
'2.718281828. ⍟ IS LOGARITHM, NATURAL ALONE AND TO A BASE'
'WITH TWO: 10⍟100 IS 2. ○1 IS PI, AND 1○X IS THE SINE OF X.'
'! IS FACTORIAL, AND 2!5 IS THE NUMBER OF WAYS TO CHOOSE 2'
'FROM 5, WHICH IS 10. TRY:'
''
'      2*10'
'      2*0.5'
'      !5'
''
'END OF LESSON 2. TYPE QUIZ 2 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q2;∆S;∆A
∆S←0
'WHAT IS 2×3+4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+14 ∆CHECK ∆A
'WHAT IS ¯3+5?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'WHAT IS 3|17, THE REMAINDER OF 17 DIVIDED BY 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'WHAT IS ⌈2.4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'WHAT IS 2*10?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1024 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L3;∆Q
'LESSON 3: VECTORS'
''
'NUMBERS TYPED IN A ROW MAKE A VECTOR, AND A FUNCTION WORKS'
'ON EVERY ELEMENT AT ONCE. TRY:'
''
'      1 2 3+4 5 6'
'      1 2 3×2'
''
'THE FIRST ADDS ELEMENT TO ELEMENT. THE SECOND MULTIPLIES'
'EVERY ELEMENT BY 2: A SINGLE NUMBER STRETCHES TO FIT.'
'TWO VECTORS OF DIFFERENT LENGTHS DO NOT FIT, AND THAT IS A'
'LENGTH ERROR.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⍳N IS THE FIRST N COUNTING NUMBERS, AND ⍴V IS HOW MANY'
'ELEMENTS V HAS. TRY:'
''
'      ⍳5'
'      2×⍳5'
'      ⍴3 4 5 6 7'
''
'⍳ IS THE INDEX GENERATOR AND ⍴ IS RHO, THE SHAPE. MUCH OF'
'APL IS BUILT FROM THESE TWO.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'WITH TWO ARGUMENTS ⍴ IS RESHAPE: N⍴V IS N ELEMENTS TAKEN'
'FROM V, CYCLING ROUND WHEN V RUNS OUT. THE COMMA JOINS TWO'
'VECTORS. TRY:'
''
'      5⍴1 2'
'      2⍴7'
'      1 2,3 4'
''
'A COMMA ALONE MAKES A VECTOR OF ANYTHING: ,7 IS A VECTOR'
'OF ONE ELEMENT, WHICH IS NOT THE SAME AS THE NUMBER 7.'
'⍴7 IS EMPTY, SINCE A LONE NUMBER HAS NO LENGTH, BUT ⍴,7'
'IS 1.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A VECTOR MAY HAVE NO ELEMENTS AT ALL. ⍳0 IS ONE, AND SO IS'
'0⍴5. IT PRINTS AS AN EMPTY LINE. TRY:'
''
'      ⍳0'
'      ⍴⍳0'
''
'EMPTY VECTORS ARE NOT A CURIOSITY: A FUNCTION THAT WORKS'
'ON A VECTOR OF ANY LENGTH WORKS ON ONE OF LENGTH ZERO,'
'AND THAT IS WHAT MAKES THE END OF A LIST NO SPECIAL CASE.'
''
'END OF LESSON 3. TYPE QUIZ 3 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q3;∆S;∆A
∆S←0
'WHAT IS ⍳4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 3 4 ∆CHECK ∆A
'HOW MANY ELEMENTS HAS 3 4 5 6 7? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 ∆CHECK ∆A
'WHAT IS 2 3 4×2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+4 6 8 ∆CHECK ∆A
'WHAT IS 5⍴1 2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 1 2 1 ∆CHECK ∆A
'WHAT IS 1 2,3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 2 3 4 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L4;∆Q
'LESSON 4: COMPARISON AND LOGIC'
''
'< ≤ = ≥ > AND ≠ COMPARE, AND ANSWER 1 FOR TRUE AND 0 FOR'
'FALSE. ON A VECTOR THEY ANSWER FOR EVERY ELEMENT. TRY:'
''
'      3<5'
'      1 2 3=2'
'      1 2 3>2'
''
'CHARACTERS COMPARE TOO: ''ABC''=''B'' IS 0 1 0.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'∧ IS AND, ∨ IS OR, AND ~ IS NOT. THEY WORK ON 1 AND 0. TRY:'
''
'      1∧0'
'      1∨0'
'      ~1 0 1'
''
'≠ ON 1 AND 0 IS EXCLUSIVE OR: 1≠1 0 IS 0 1. ⍲ AND ⍱ ARE'
'NAND AND NOR, THE TWO NEGATED.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'1 AND 0 ARE NUMBERS, NOT A SEPARATE KIND OF VALUE. SO A'
'COMPARISON CAN BE USED IN ARITHMETIC. TRY:'
''
'      2×1 2 3>1'
'      (1 2 3>1)×10 20 30'
''
'MULTIPLYING BY A COMPARISON KEEPS THE ELEMENTS THAT PASS'
'AND ZEROES THE REST. THE NEXT LESSON COUNTS THEM.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'⌈ AND ⌊ FROM LESSON 2 ARE COMPARISONS OF A KIND: 3⌈5 IS'
'THE LARGER. ON 1 AND 0, ⌈ IS OR AND ⌊ IS AND. TRY:'
''
'      1⌈0'
'      1⌊0'
'      3 1 4⌈2'
''
'END OF LESSON 4. TYPE QUIZ 4 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q4;∆S;∆A
∆S←0
'WHAT IS 1 2 3>2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 0 1 ∆CHECK ∆A
'WHAT IS 1∧0?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHAT IS ~1 0 1?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 1 0 ∆CHECK ∆A
'WHAT IS 3≠3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 ∆CHECK ∆A
'WHAT IS (1 2 3>1)×10 20 30?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+0 20 30 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L5;∆Q
'LESSON 5: REDUCTION AND SCAN'
''
'F/V PUTS THE FUNCTION F BETWEEN THE ELEMENTS OF V. +/ IS'
'THE SUM, ×/ THE PRODUCT, ⌈/ THE LARGEST, ⌊/ THE SMALLEST.'
'TRY:'
''
'      +/1 2 3 4'
'      ×/2 3 4'
'      ⌈/3 9 2'
''
'THIS IS REDUCTION, AND / IS AN OPERATOR: IT TAKES A'
'FUNCTION AND MAKES A NEW ONE. -/1 2 3 IS 1-2-3 READ FROM'
'THE RIGHT, 1-(2-3), WHICH IS 2.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'ON 1 AND 0, ∧/ ASKS WHETHER ALL ARE 1 AND ∨/ WHETHER ANY'
'IS. +/ COUNTS THEM. TRY:'
''
'      ∧/1 1 0'
'      ∨/1 2 3>2'
'      +/2 4 6 8>3'
''
'THE LAST COUNTS HOW MANY ELEMENTS EXCEED 3. NO LOOP WAS'
'WRITTEN: THE COMPARISON MADE A VECTOR OF 1S AND 0S, AND'
'THE REDUCTION SUMMED IT.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'F\V IS SCAN: EVERY REDUCTION ALONG THE WAY. +\ IS THE'
'RUNNING TOTAL. TRY:'
''
'      +\1 2 3 4'
'      ×\1 2 3 4'
'      ⌈\3 1 4 1 5'
''
'×\⍳N IS THE FACTORIALS, AND ⌈\ IS THE LARGEST SO FAR.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'THE AVERAGE OF A VECTOR IS ITS SUM OVER ITS LENGTH:'
''
'      (+/2 4 6)÷⍴2 4 6'
''
'REDUCING AN EMPTY VECTOR GIVES THE VALUE THAT LEAVES THE'
'FUNCTION ALONE: +/⍳0 IS 0 AND ×/⍳0 IS 1. SO THE SUM OF'
'NOTHING IS 0, AS IT SHOULD BE, AND NO CASE IS SPECIAL.'
''
'END OF LESSON 5. TYPE QUIZ 5 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q5;∆S;∆A
∆S←0
'WHAT IS +/1 2 3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+10 ∆CHECK ∆A
'WHAT IS ×/2 3 4?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+24 ∆CHECK ∆A
'WHAT IS +\1 2 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+1 3 6 ∆CHECK ∆A
'WHAT IS ⌈/3 9 2?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+9 ∆CHECK ∆A
'HOW MANY OF 2 4 6 8 EXCEED 3? TYPE THE NUMBER.'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
∇∆L6;∆Q
'LESSON 6: SELECTION'
''
'BRACKETS AFTER A VECTOR PICK ELEMENTS BY POSITION, COUNTING'
'FROM 1. THE INDEX MAY BE A VECTOR TOO. TRY:'
''
'      V←10 20 30 40'
'      V[3]'
'      V[1 3]'
'      V[4 3 2 1]'
''
'THE ARROW, ←, GIVES V ITS VALUE, AND V KEEPS IT UNTIL YOU'
'CHANGE IT. A LINE THAT ONLY ASSIGNS PRINTS NOTHING. AN'
'INDEXED NAME ON THE LEFT OF THE ARROW CHANGES ONE ELEMENT:'
'V[2]←25, AND THEN V.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'↑ TAKES THE FIRST N ELEMENTS AND ↓ DROPS THEM; A NEGATIVE'
'N COUNTS FROM THE END. TRY:'
''
'      2↑V'
'      ¯1↑V'
'      1↓V'
'      ¯2↓V'
''
'⌽ REVERSES, AND N⌽V ROTATES BY N: 1⌽V MOVES THE FIRST'
'ELEMENT TO THE END.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'A VECTOR OF 1S AND 0S ON THE LEFT OF / SELECTS: THIS IS'
'COMPRESSION, AND WITH A COMPARISON IT IS HOW APL FILTERS.'
'TRY:'
''
'      (V>15)/V'
'      1 0 1 1/V'
'      1 0 1 1\1 2 3'
''
'THE LAST IS EXPANSION: THE 0 OPENS A GAP, FILLED WITH 0.'
∆TRY
∆Q←∆PAUSE
→∆Q/0
'∊ ASKS WHETHER EACH ELEMENT ON THE LEFT IS SOMEWHERE ON'
'THE RIGHT, AND V⍳X ASKS WHERE: THE POSITION OF X IN V, OR'
'ONE PAST THE END IF IT IS NOT THERE. TRY:'
''
'      30∊V'
'      V⍳30'
'      V⍳99'
''
'END OF LESSON 6. TYPE QUIZ 6 TO CHECK, OR NEXT TO GO ON.'
∇
∇∆Q6;∆S;∆A
∆S←0
'WHAT IS 2↑5 6 7 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+5 6 ∆CHECK ∆A
'WHAT IS 1↓5 6 7 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+6 7 8 ∆CHECK ∆A
'WHAT IS ⌽1 2 3?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+3 2 1 ∆CHECK ∆A
'WHAT IS 1 0 1/7 8 9?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+7 9 ∆CHECK ∆A
'WHAT IS 7 8 9⍳8, THE POSITION OF 8?'
∆A←∆READ
→('STOP' ∆IS ∆A)/0
∆S←∆S+2 ∆CHECK ∆A
'YOU GOT ';∆S;' OF 5.'
∇
