⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 11.00.00 09/25/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID DRILL
DYA←'+-×÷⌈⌊|*<≤=≥>≠∧∨'
MON←'-×|⌈⌊⍳⍴⌽'
STOP←'STOP'
∇DESCRIBE
'DRILL -- EXERCISES IN APL, MADE AT RANDOM AND MARKED.'
''
'   SHOW N      PRINT N EXERCISES, EACH WITH ITS ANSWER.'
''
'THE DRILL ITSELF, WHICH ASKS AND MARKS, IS NOT HERE YET.'
'MON AND DYA ARE THE GLYPHS IT DRAWS ON, ONE-ARGUMENT AND'
'TWO-ARGUMENT; AN EXERCISE IS ONE OF THEM ON SMALL WHOLE'
'NUMBERS, SCALARS OR VECTORS, CHOSEN SO THAT THE ANSWER IS'
'WHOLE WHERE THE FUNCTION ALLOWS.'
∇
∇SHOW N;∆I;∆E;∆V
⍝ N EXERCISES, EACH FOLLOWED BY ITS ANSWER.
∆I←0
L:→(∆I≥N)/0
∆I←∆I+1
∆NEW
∆E
∆V
→L
∇
∇R←F ∆MON X
⍝ THE MONADIC FUNCTION WHOSE GLYPH IS F, ON X. THERE IS NO EXECUTE
⍝ IN (A), SO A GLYPH CHOSEN AT RANDOM IS APPLIED BY THIS TABLE.
→(NEG,SGN,MAG,CEIL,FLR,IOTA,SHAPE,REV)[MON⍳F]
NEG:R←-X
→0
SGN:R←×X
→0
MAG:R←|X
→0
CEIL:R←⌈X
→0
FLR:R←⌊X
→0
IOTA:R←⍳X
→0
SHAPE:R←⍴X
→0
REV:R←⌽X
∇
∇R←∆DYA F
⍝ ∆X F ∆Y, FOR THE GLYPH F: THE DYADIC TABLE. ∆X AND ∆Y ARE THE
⍝ CALLER'S, READ HERE AS ANY LOCAL OF A CALLER CAN BE.
→(ADD,SUB,MUL,DIV,MAX,MIN,RES,POW,LT,LE,EQ,GE,GT,NE,AND,OR)[DYA⍳F]
ADD:R←∆X+∆Y
→0
SUB:R←∆X-∆Y
→0
MUL:R←∆X×∆Y
→0
DIV:R←∆X÷∆Y
→0
MAX:R←∆X⌈∆Y
→0
MIN:R←∆X⌊∆Y
→0
RES:R←∆X|∆Y
→0
POW:R←∆X*∆Y
→0
LT:R←∆X<∆Y
→0
LE:R←∆X≤∆Y
→0
EQ:R←∆X=∆Y
→0
GE:R←∆X≥∆Y
→0
GT:R←∆X>∆Y
→0
NE:R←∆X≠∆Y
→0
AND:R←∆X∧∆Y
→0
OR:R←∆X∨∆Y
∇
∇R←∆CHARS N;∆D;∆I;∆S
⍝ A WHOLE NUMBER, OR A VECTOR OF THEM, AS APL PRINTS IT: DIGITS BY
⍝ ENCODE, A HIGH MINUS, A BLANK BETWEEN. (A) HAS NO FORMAT.
R←''
N←,N
∆I←0
L:→(∆I≥⍴N)/0
∆I←∆I+1
∆S←N[∆I]
∆D←'0123456789'[1+((1+⌊10⍟1⌈|∆S)⍴10)⊤|∆S]
→(∆S≥0)/POS
∆D←'¯',∆D
POS:R←R,((∆I>1)/' '),∆D
→L
∇
∇∆NEW;∆F;∆X;∆Y;∆K
⍝ CHOOSE AN EXERCISE: SET THE CALLER'S ∆E TO ITS CHARACTERS AND ∆V
⍝ TO ITS VALUE. ONE-ARGUMENT OR TWO-ARGUMENT, THEN THE OPERANDS BY
⍝ WHAT THE FUNCTION WANTS, SO THAT THE ANSWER IS WHOLE WHERE IT CAN
⍝ BE: A MULTIPLE FOR DIVISION, A SMALL POWER, A DIVISOR OF 1 TO 5
⍝ FOR RESIDUE, 1 AND 0 FOR AND AND OR. TWO VECTORS ARE THE SAME
⍝ LENGTH, SO NOTHING IS A LENGTH ERROR.
→(1=?2)/ONE
∆F←DYA[?⍴DYA]
∆K←?4
∆X←∆SMALL ∆K∊2 4
∆Y←∆SMALL ∆K=3
→(∆K≠4)/SHAPED
∆Y←¯1+?(⍴∆X)⍴10
SHAPED:→(∆F='÷')/DIV
→(∆F='*')/POW
→(∆F='|')/RES
→(∆F∊'∧∨')/LOG
→DONE
DIV:∆Y←1+∆Y
∆X←∆Y×¯1+?(⍴∆X)⍴7
→DONE
POW:∆Y←⌊∆Y÷3
→DONE
RES:∆X←1+5|∆X
→DONE
LOG:∆X←2|∆X
∆Y←2|∆Y
DONE:∆E←(∆CHARS ∆X),∆F,∆CHARS ∆Y
∆V←∆DYA ∆F
→0
ONE:∆F←MON[?⍴MON]
∆X←∆SMALL 1=?2
→(∆F='⍳')/IOTA
→(∆F∊'⍴⌽')/VEC
→(∆F='-')/SIGNED
→DONE1
IOTA:∆X←?6
→DONE1
VEC:∆X←∆SMALL 1
→DONE1
SIGNED:∆X←∆X-4
DONE1:∆E←∆F,∆CHARS ∆X
∆V←∆F ∆MON ∆X
∇
∇R←∆SMALL V
⍝ SMALL WHOLE NUMBERS FROM 0 TO 9: A VECTOR OF 2 TO 5 IF V, A
⍝ SCALAR IF NOT.
→V/VEC
R←¯1+?10
→0
VEC:R←¯1+?(1+?4)⍴10
∇
