⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 15.30.00 09/25/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID DRILL
DYA←'+-×÷⌈⌊|*<≤=≥>≠∧∨'
MON←'-×|⍳⍴⌽'
RED←'+×⌈⌊'
STOP←'STOP'
STR←'[⍳∊↑↓⌽/'
∇DESCRIBE
'DRILL -- EXERCISES IN APL, MADE AT RANDOM AND MARKED.'
''
'   EASY        ONE FUNCTION ON SINGLE NUMBERS.'
'   DRILL       ONE OR TWO FUNCTIONS ON VECTORS.'
'   HARD        TWO FUNCTIONS, PARENTHESES, REDUCTIONS.'
'   SHOW N      PRINT N EXERCISES, EACH WITH ITS ANSWER.'
''
'EACH ASKS WHICH FUNCTIONS TO DRILL, THEN PRINTS AN EXERCISE'
'AND A QUAD PROMPT. TYPE THE ANSWER AS APL: A NUMBER, OR A'
'VECTOR, OR AN EXPRESSION THAT MAKES ONE. STOP ENDS THE DRILL'
'AND PRINTS THE SCORE. HOWDRILL SAYS MORE.'
∇
∇HOWDRILL
'THE TOPICS, ASKED FOR AT THE START:'
''
'   ARITHMETIC  + - × ÷ | *, AND - × | ON ONE ARGUMENT'
'   COMPARE     < ≤ = ≥ > ≠ ∧ ∨, ANSWERING 1 AND 0'
'   MAXMIN      ⌈ AND ⌊ BETWEEN TWO ARGUMENTS'
'   REDUCE      +/ ×/ ⌈/ ⌊/ OVER VECTORS, AND OVER + - ×'
'   INDEX       V[I], INDEX-OF V⍳X AND MEMBERSHIP X∊V'
'   STRUCTURE   TAKE, DROP, ROTATE, COMPRESS, AND ⍳ ⍴ ⌽'
'   ALL         EVERYTHING ABOVE'
''
'THE NUMBERS ARE SMALL AND WHOLE, AND CHOSEN SO THAT THE'
'ANSWER IS WHOLE WHERE THE FUNCTION ALLOWS. AN ANSWER IS'
'RIGHT WHEN ITS VALUES AND ITS SHAPE ARE; A SINGLE NUMBER'
'FOR A ONE-ELEMENT VECTOR PASSES WITH A REMARK. A WRONG'
'ANSWER SHOWS THE RIGHT ONE, AND THREE WRONG IN A ROW SHOW'
'THE EXERCISE WORKED OUT. THE EXERCISES COME IN THE SAME'
'ORDER AFTER EVERY LOAD, SO A DRILL CAN BE RUN AGAIN.'
∇
∇EASY
∆RUN 1
∇
∇DRILL
∆RUN 2
∇
∇HARD
∆RUN 3
∇
∇SHOW N;∆I;∆E;∆V;∆E1;∆V1;∆F1;∆F2;∆H1;∆H2;∆M;∆D;∆R;∆O;∆C;∆S
⍝ N EXERCISES FROM EVERY TOPIC AT THE DRILL LEVEL, EACH FOLLOWED
⍝ BY ITS ANSWER.
∆M←MON
∆D←DYA
∆R←RED
∆O←'+-×⌈⌊<≤=≥>≠'
∆C←DYA
∆S←STR
∆I←0
L:→(∆I≥N)/0
∆I←∆I+1
∆NEW 2
∆E
∆V
→L
∇
∇∆RUN ∆L;∆E;∆V;∆E1;∆V1;∆F1;∆F2;∆H1;∆H2;∆M;∆D;∆R;∆O;∆C;∆S;∆A;∆N;∆T;∆W;∆Q
⍝ THE DRILL AT LEVEL ∆L: THE TOPIC, THEN EXERCISES UNTIL STOP.
⍝ ∆NEW SETS ∆E, ∆V AND THE REST FOR THE ONE IN HAND.
∆MENU
→('STOP' ∆IS ∆M)/0
∆N←0
∆T←0
∆W←0
L:∆NEW ∆L
∆E
∆A←⎕
→('STOP' ∆IS ∆A)/END
∆N←∆N+1
∆Q←∆V ∆CHECK ∆A
∆T←∆T+∆Q
∆W←(~∆Q)×∆W+1
→(∆W<3)/L
∆WORK
∆W←0
→L
END:'STOPPED. ';∆T;' RIGHT OF ';∆N;'.'
∇
∇∆MENU;∆T
⍝ ASK THE TOPIC, AND SET THE CALLER'S TABLES: ∆M THE ONE-ARGUMENT
⍝ GLYPHS, ∆D THE TWO-ARGUMENT, ∆R THE REDUCTIONS, ∆S THE STRUCTURAL
⍝ AND INDEXING FUNCTIONS, ∆C THE GLYPHS ALLOWED INSIDE A COMPOSED
⍝ EXERCISE AND ∆O THOSE ALLOWED OUTSIDE ONE, WHERE THE INNER VALUE
⍝ MAY BE ANYTHING. ∆M IS STOP IF THE READER STOPS HERE.
'WHICH FUNCTIONS? ARITHMETIC, COMPARE, MAXMIN, REDUCE, INDEX,'
'STRUCTURE OR ALL.'
ASK:⍞←'TOPIC: '
∆T←⍞
∆M←STOP
→('STOP' ∆IS ∆T)/0
∆M←''
∆D←''
∆R←''
∆O←''
∆C←''
∆S←''
→('ARITHMETIC' ∆IS ∆T)/ARITH
→('COMPARE' ∆IS ∆T)/COMP
→('MAXMIN' ∆IS ∆T)/MAXMIN
→('REDUCE' ∆IS ∆T)/REDUCE
→('INDEX' ∆IS ∆T)/INDEX
→('STRUCTURE' ∆IS ∆T)/STRUCT
→(('ALL' ∆IS ∆T)∨0=⍴,∆T)/ALL
'TYPE ONE OF THOSE, OR STOP.'
→ASK
ARITH:∆M←'-×|'
∆D←'+-×÷|*'
∆C←∆D
∆O←'+-×'
→0
COMP:∆D←'<≤=≥>≠∧∨'
∆C←∆D
∆O←'<≤=≥>≠'
→0
MAXMIN:∆D←'⌈⌊'
∆C←∆D
∆O←∆D
→0
REDUCE:∆R←RED
∆C←'+-×'
→0
INDEX:∆S←'[⍳∊'
→0
STRUCT:∆M←'⍳⍴⌽'
∆S←'↑↓⌽/'
→0
ALL:∆M←MON
∆D←DYA
∆R←RED
∆C←DYA
∆O←'+-×⌈⌊<≤=≥>≠'
∆S←STR
∇
∇R←W ∆IS A
⍝ IS THE ANSWER A THE WORD W? AT A QUAD PROMPT, STOP IS THE
⍝ VARIABLE OF THAT NAME, WHICH HOLDS ITSELF.
R←((⍴,W)=⍴,A)∧∧/(,W)=(⍴,W)↑,A
∇
∇R←W ∆CHECK A
⍝ IS THE ANSWER A THE WANTED VALUE W? SAME COUNT, SAME VALUES,
⍝ AND THE SAME RANK; A SCALAR FOR A ONE-ELEMENT VECTOR PASSES
⍝ WITH A REMARK. R IS 1 FOR RIGHT.
R←0
→((×/⍴,W)≠×/⍴,A)/WRONG
→(~∧/,(,W)=,A)/WRONG
→((⍴⍴W)=⍴⍴A)/RIGHT
'RIGHT VALUE, THOUGH ONE IS A SCALAR AND ONE A VECTOR.'
R←1
→0
RIGHT:'RIGHT.'
R←1
→0
WRONG:'NO. THE ANSWER IS:'
W
∇
∇∆WORK
⍝ THREE WRONG IN A ROW: THE EXERCISE IN HAND, WORKED OUT. THE
⍝ INNER STEP FIRST IF THERE IS ONE, THEN A WORD ON EACH FUNCTION.
'THREE WRONG IN A ROW. WORKED OUT:'
→(0=⍴∆E1)/ONE
'   FIRST, ',∆E1,' IS'
'   ';∆V1
'   THEN ',∆E,' IS'
'   ';∆V
∆F2 ∆HINT ∆H2
∆F1 ∆HINT ∆H1
→0
ONE:'   ',∆E,' IS'
'   ';∆V
∆F1 ∆HINT ∆H1
∇
∇F ∆HINT H
⍝ A WORD ON THE GLYPH F AS USED: H IS 1 WITH ONE ARGUMENT, 2 WITH
⍝ TWO, 3 IN A REDUCTION, 4 A STRUCTURAL OR INDEXING FUNCTION.
→(MONH,DYAH,REDH,STRH)[H]
MONH:→(NEG,SGN,MAG,IOTA,SHAPE,REV)[MON⍳F]
NEG:'   -X IS X NEGATED.'
→0
SGN:'   ×X IS THE SIGN OF X: ¯1, 0 OR 1.'
→0
MAG:'   |X IS THE MAGNITUDE OF X, WITH NO SIGN.'
→0
IOTA:'   ⍳N IS THE FIRST N COUNTING NUMBERS.'
→0
SHAPE:'   ⍴V IS HOW MANY ELEMENTS V HAS.'
→0
REV:'   ⌽V IS V REVERSED.'
→0
DYAH:→(ADD,SUB,MUL,DIV,MAX,MIN,RES,POW,LT,LE,EQ,GE,GT,NE,AND,OR)[DYA⍳F]
ADD:'   + ADDS, ELEMENT BY ELEMENT.'
→0
SUB:'   - SUBTRACTS THE RIGHT FROM THE LEFT.'
→0
MUL:'   × MULTIPLIES, ELEMENT BY ELEMENT.'
→0
DIV:'   ÷ DIVIDES THE LEFT BY THE RIGHT.'
→0
MAX:'   ⌈ IS THE LARGER OF EACH PAIR.'
→0
MIN:'   ⌊ IS THE SMALLER OF EACH PAIR.'
→0
RES:'   A|B IS THE REMAINDER OF B DIVIDED BY A.'
→0
POW:'   A*B IS A TO THE POWER B.'
→0
LT:'   < IS 1 WHERE THE LEFT IS LESS, 0 ELSEWHERE.'
→0
LE:'   ≤ IS 1 WHERE THE LEFT IS LESS OR EQUAL, 0 ELSEWHERE.'
→0
EQ:'   = IS 1 WHERE THE TWO ARE EQUAL, 0 ELSEWHERE.'
→0
GE:'   ≥ IS 1 WHERE THE LEFT IS GREATER OR EQUAL, 0 ELSEWHERE.'
→0
GT:'   > IS 1 WHERE THE LEFT IS GREATER, 0 ELSEWHERE.'
→0
NE:'   ≠ IS 1 WHERE THE TWO DIFFER, 0 ELSEWHERE.'
→0
AND:'   ∧ IS 1 WHERE BOTH ARE 1.'
→0
OR:'   ∨ IS 1 WHERE EITHER IS 1.'
→0
REDH:→(SUM,PROD,BIG,SMALL)[RED⍳F]
SUM:'   +/ IS THE SUM OF THE ELEMENTS.'
→0
PROD:'   ×/ IS THE PRODUCT OF THE ELEMENTS.'
→0
BIG:'   ⌈/ IS THE LARGEST ELEMENT.'
→0
SMALL:'   ⌊/ IS THE SMALLEST ELEMENT.'
→0
STRH:→(BRK,IDX,MEM,TAKE,DROP,ROT,COMP)[STR⍳F]
BRK:'   (V)[I] PICKS THE ELEMENTS OF V AT THE POSITIONS I.'
→0
IDX:'   V⍳X IS WHERE X FIRST OCCURS IN V, OR ONE PAST THE END.'
→0
MEM:'   X∊V IS 1 WHERE X IS SOMEWHERE IN V, 0 WHERE NOT.'
→0
TAKE:'   N↑V IS THE FIRST N ELEMENTS OF V; A NEGATIVE N, THE LAST.'
→0
DROP:'   N↓V IS V WITHOUT ITS FIRST N; A NEGATIVE N, ITS LAST.'
→0
ROT:'   N⌽V ROTATES V LEFT BY N; A NEGATIVE N, RIGHT.'
→0
COMP:'   B/V KEEPS THE ELEMENTS OF V WHERE B IS 1.'
∇
∇∆NEW ∆L;∆F;∆G;∆X;∆Y;∆Z;∆T;∆K
⍝ CHOOSE AN EXERCISE AT LEVEL ∆L FROM THE CALLER'S TABLES, AND SET
⍝ THE CALLER'S ∆E, ITS CHARACTERS, AND ∆V, ITS VALUE; ∆E1 AND ∆V1,
⍝ THE INNER STEP WHEN THERE IS ONE; ∆F1 AND ∆F2 THE GLYPHS AND ∆H1
⍝ AND ∆H2 HOW EACH IS USED, FOR THE HINTS. LEVEL 1 IS ONE FUNCTION
⍝ ON SCALARS, OR ON A SHORT VECTOR WHERE IT MUST HAVE ONE; 2 ONE
⍝ FUNCTION ON VECTORS, OR TWO; 3 TWO FUNCTIONS, IN A CHAIN, IN
⍝ PARENTHESES, OR UNDER A REDUCTION.
∆E1←''
∆V1←0
∆F2←' '
∆H2←1
∆K←∆KIND ∆L
→(MON1,DYA1,RED1,CHAIN,PAREN,REDCH,STR1,REDST)[∆K]
MON1:∆F←∆M[?⍴∆M]
∆X←∆SMALL ∆L>1
→(∆F='⍳')/IOTA
→(∆F∊'⍴⌽')/VEC
→(∆F='-')/SIGNED
→DONE1
IOTA:∆X←?6
→DONE1
VEC:∆X←∆SMALL 1
→DONE1
SIGNED:∆X←∆X-4
DONE1:∆E←∆F,∆CHARS ∆X
∆V←∆F ∆MON ∆X
∆F1←∆F
∆H1←1
→0
DYA1:∆F←∆D[?⍴∆D]
∆G←∆F
∆PAIR ∆L>1
∆E←(∆CHARS ∆X),∆F,∆CHARS ∆Y
∆V←∆DYA ∆F
∆F1←∆F
∆H1←2
→0
RED1:∆F←∆R[?⍴∆R]
∆X←¯1+?((1+∆L)⌊1+?4)⍴10
∆E←∆F,'/',∆CHARS ∆X
∆V←∆F ∆REDUCE ∆X
∆F1←∆F
∆H1←3
→0
CHAIN:∆G←∆C[?⍴∆C]
∆F←∆O[?⍴∆O]
∆PAIR 1+∆L=3
∆E1←(∆CHARS ∆X),∆G,∆CHARS ∆Y
∆V1←∆DYA ∆G
∆Z←∆OUTER
∆E←(∆CHARS ∆Z),∆F,∆E1
∆Y←∆V1
∆X←∆Z
∆V←∆DYA ∆F
∆F1←∆F
∆H1←2
∆F2←∆G
∆H2←2
→0
PAREN:∆G←∆C[?⍴∆C]
∆F←∆O[?⍴∆O]
∆PAIR 1+∆L=3
∆E1←(∆CHARS ∆X),∆G,∆CHARS ∆Y
∆V1←∆DYA ∆G
∆Z←∆OUTER
∆E←'(',∆E1,')',∆F,∆CHARS ∆Z
∆X←∆V1
∆Y←∆Z
∆V←∆DYA ∆F
∆F1←∆F
∆H1←2
∆F2←∆G
∆H2←2
→0
REDCH:∆G←∆C[?⍴∆C]
∆F←∆R[?⍴∆R]
∆PAIR 1+∆L=3
∆E1←(∆CHARS ∆X),∆G,∆CHARS ∆Y
∆V1←∆DYA ∆G
∆E←∆F,'/',∆E1
∆V←∆F ∆REDUCE ∆V1
∆F1←∆F
∆H1←3
∆F2←∆G
∆H2←2
→0
STR1:∆G←∆S[?⍴∆S]
∆SPAIR ∆L
∆E←∆SHOWS
∆V←∆STR ∆G
∆F1←∆G
∆H1←4
→0
REDST:∆G←∆S[?⍴∆S]
∆F←RED[?⍴RED]
∆SPAIR ∆L
∆E1←∆SHOWS
∆V1←∆STR ∆G
∆E←∆F,'/',∆E1
∆V←∆F ∆REDUCE ∆V1
∆F1←∆F
∆H1←3
∆F2←∆G
∆H2←4
∇
∇∆SPAIR L
⍝ SET THE CALLER'S ∆X AND ∆Y FOR THE STRUCTURAL OR INDEXING GLYPH
⍝ ∆G: A VECTOR OF 2 TO 5 (SHORTER AT LEVEL 1) AND WHAT THE GLYPH
⍝ WANTS BESIDE IT, CHOSEN SO THAT THE EXERCISE IS VALID AND ITS
⍝ VALUE IS NOT EMPTY: INDICES WITHIN RANGE, A TAKE OR DROP OR
⍝ ROTATION WITHIN THE LENGTH, A COMPRESSION KEEPING SOMETHING.
∆Y←¯1+?((2+L)⌊1+?4)⍴10
→(BRK,IDX,MEM,TAKE,DROP,ROT,COMP)[STR⍳∆G]
BRK:∆X←∆Y
∆Y←?⍴∆X
→(L=1)/0
∆Y←?(1+?2)⍴⍴∆X
→0
IDX:∆X←∆Y
∆Y←∆X[?⍴∆X]
→(1≠?4)/0
∆Y←9+?5
→0
MEM:∆X←¯1+?10
→(L=1)/0
∆X←¯1+?(1+?2)⍴10
→0
TAKE:∆X←(?⍴∆Y)×∆SIGN
→0
DROP:∆X←(¯1+?⍴∆Y)×∆SIGN
→0
ROT:∆X←(?⍴∆Y)×∆SIGN
→0
COMP:∆X←1=?(⍴∆Y)⍴2
→(∨/∆X)/0
∆X[?⍴∆X]←1
∇
∇R←∆SIGN
⍝ 1, OR ¯1 ONE TIME IN THREE.
R←1-2×1=?3
∇
∇R←∆SHOWS
⍝ THE CHARACTERS OF THE CALLER'S ∆X ∆G ∆Y: BRACKETS FOR INDEXING,
⍝ THE GLYPH BETWEEN FOR THE REST.
→(∆G='[')/BRK
R←(∆CHARS ∆X),∆G,∆CHARS ∆Y
→0
BRK:R←'(',(∆CHARS ∆X),')[',(∆CHARS ∆Y),']'
∇
∇R←∆STR F
⍝ THE STRUCTURAL OR INDEXING FUNCTION WHOSE GLYPH IS F, BETWEEN THE
⍝ CALLER'S ∆X AND ∆Y.
→(BRK,IDX,MEM,TAKE,DROP,ROT,COMP)[STR⍳F]
BRK:R←∆X[∆Y]
→0
IDX:R←∆X⍳∆Y
→0
MEM:R←∆X∊∆Y
→0
TAKE:R←∆X↑∆Y
→0
DROP:R←∆X↓∆Y
→0
ROT:R←∆X⌽∆Y
→0
COMP:R←∆X/∆Y
∇
∇R←∆KIND L
⍝ WHICH SHAPE OF EXERCISE: 1 ONE-ARGUMENT, 2 TWO-ARGUMENT, 3 A
⍝ REDUCTION, 4 A CHAIN A F B G C, 5 (A F B) G C, 6 F/A G B, 7 A
⍝ STRUCTURAL OR INDEXING FUNCTION, 8 A REDUCTION OVER ONE (ANY
⍝ REDUCTION: A TOPIC WITH ∆S HAS THEM WHETHER OR NOT IT DRILLS THEM
⍝ ALONE). BY THE LEVEL, AND BY WHICH TABLES THE TOPIC FILLED.
R←(0<⍴∆M),(0<⍴∆D),0<⍴∆R
R←R,((0<⍴∆C)∧0<⍴∆O),((0<⍴∆C)∧0<⍴∆O),(0<⍴∆C)∧0<⍴∆R
R←R,(0<⍴∆S),0<⍴∆S
→(L=1)/ONE
→(L=2)/TWO
R←R∧0 0 0 1 1 1 0 1
→PICK
ONE:R←R∧1 1 1 0 0 0 1 0
→PICK
TWO:→(1=?2)/ONE
PICK:R←R/⍳8
R←R[?⍴R]
∇
∇∆PAIR V
⍝ SET THE CALLER'S ∆X AND ∆Y FOR THE GLYPH ∆G BETWEEN THEM:
⍝ SCALARS IF V IS 0; SCALARS OR VECTORS OF ONE LENGTH IF 1; AT
⍝ LEAST ONE A VECTOR IF 2. THE OPERANDS KEEP
⍝ THE ANSWER WHOLE WHERE THE FUNCTION ALLOWS: A MULTIPLE FOR
⍝ DIVISION, A SMALL POWER, A DIVISOR OF 1 TO 5 FOR RESIDUE, 1 AND
⍝ 0 FOR AND AND OR.
∆K←((V=1)×?4)+(V=2)×1+?3
∆X←∆SMALL ∆K∊2 4
∆Y←∆SMALL ∆K=3
→(∆K≠4)/SHAPED
∆Y←¯1+?(⍴∆X)⍴10
SHAPED:→(∆G='÷')/DIV
→(∆G='*')/POW
→(∆G='|')/RES
→(∆G∊'∧∨')/LOG
→0
DIV:∆Y←1+∆Y
∆X←∆Y×¯1+?(⍴∆X)⍴7
→0
POW:∆Y←⌊∆Y÷3
→0
RES:∆X←1+5|∆X
→0
LOG:∆X←2|∆X
∆Y←2|∆Y
∇
∇R←∆OUTER
⍝ THE OPERAND OUTSIDE A COMPOSED EXERCISE: A SCALAR, OR A VECTOR
⍝ SHAPED LIKE THE CALLER'S INNER VALUE ∆V1, SO THAT IT CONFORMS.
→(1=?2)/SCAL
R←¯1+?(⍴∆V1)⍴10
→0
SCAL:R←∆SMALL 0
∇
∇R←F ∆REDUCE X
⍝ THE REDUCTION WHOSE GLYPH IS F, OVER X.
→(SUM,PROD,BIG,SMALL)[RED⍳F]
SUM:R←+/X
→0
PROD:R←×/X
→0
BIG:R←⌈/X
→0
SMALL:R←⌊/X
∇
∇R←F ∆MON X
⍝ THE MONADIC FUNCTION WHOSE GLYPH IS F, ON X. THERE IS NO EXECUTE
⍝ IN (A), SO A GLYPH CHOSEN AT RANDOM IS APPLIED BY THIS TABLE.
→(NEG,SGN,MAG,IOTA,SHAPE,REV)[MON⍳F]
NEG:R←-X
→0
SGN:R←×X
→0
MAG:R←|X
→0
IOTA:R←⍳X
→0
SHAPE:R←⍴X
→0
REV:R←⌽X
∇
∇R←∆DYA F
⍝ ∆X F ∆Y, FOR THE GLYPH F: THE DYADIC TABLE. ∆X AND ∆Y ARE THE
⍝ CALLER'S, READ HERE AS ANY LOCAL OF A CALLER CAN BE.
→(ADD,SUB,MUL,DIV,MAX,MIN,RES,POW,LT,LE,EQ,GE,GT,NE,AND,OR)[DYA⍳F]
ADD:R←∆X+∆Y
→0
SUB:R←∆X-∆Y
→0
MUL:R←∆X×∆Y
→0
DIV:R←∆X÷∆Y
→0
MAX:R←∆X⌈∆Y
→0
MIN:R←∆X⌊∆Y
→0
RES:R←∆X|∆Y
→0
POW:R←∆X*∆Y
→0
LT:R←∆X<∆Y
→0
LE:R←∆X≤∆Y
→0
EQ:R←∆X=∆Y
→0
GE:R←∆X≥∆Y
→0
GT:R←∆X>∆Y
→0
NE:R←∆X≠∆Y
→0
AND:R←∆X∧∆Y
→0
OR:R←∆X∨∆Y
∇
∇R←∆CHARS N;∆D;∆I;∆S
⍝ A WHOLE NUMBER, OR A VECTOR OF THEM, AS APL PRINTS IT: DIGITS BY
⍝ ENCODE, A HIGH MINUS, A BLANK BETWEEN. (A) HAS NO FORMAT.
R←''
N←,N
∆I←0
L:→(∆I≥⍴N)/0
∆I←∆I+1
∆S←N[∆I]
∆D←'0123456789'[1+((1+⌊10⍟1⌈|∆S)⍴10)⊤|∆S]
→(∆S≥0)/POS
∆D←'¯',∆D
POS:R←R,((∆I>1)/' '),∆D
→L
∇
∇R←∆SMALL V
⍝ SMALL WHOLE NUMBERS FROM 0 TO 9: A VECTOR OF 2 TO 5 IF V, A
⍝ SCALAR IF NOT.
→V/VEC
R←¯1+?10
→0
VEC:R←¯1+?(1+?4)⍴10
∇
