⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 16.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID MATH
∇DESCRIBE
'MATH -- NUMBER THEORY AND COMBINATORICS ON WHOLE NUMBERS.'
''
'   PRIMES N      THE PRIMES UP TO N, BY A SIEVE.'
'   ISPRIME N     1 IF N IS PRIME.'
'   FACTORS N     THE PRIME FACTORS OF N, WITH REPETITION.'
'   DIVISORS N    EVERY DIVISOR OF N.'
'   A GCD B       THE GREATEST COMMON DIVISOR, BY EUCLID.'
'   A LCM B       THE LEAST COMMON MULTIPLE.'
'   TOTIENT N     HOW MANY OF 1 TO N ARE COPRIME TO N.'
'   FIB N         THE FIRST N FIBONACCI NUMBERS.'
'   PASCAL N      ROWS 0 TO N OF PASCAL''S TRIANGLE, AS A MATRIX.'
'   PERMS N       EVERY PERMUTATION OF 1 TO N, ONE A ROW.'
'   K COMBS N     EVERY K OF 1 TO N, ONE A ROW.'
'   B BASE N      THE DIGITS OF N IN BASE B.'
'   B UNBASE D    THE NUMBER WITH DIGITS D IN BASE B.'
'   DIGITS N      THE DECIMAL DIGITS OF N.'
'   ROMAN N       N IN ROMAN NUMERALS.'
'   COLLATZ N     FROM N TO 1: HALVE, OR TREBLE AND ADD ONE.'
''
'TYPE HOWPERMS, HOWCOMBS OR HOWBASE FOR MORE.'
∇
∇HOWPERMS
'PERMS N IS A MATRIX OF !N ROWS AND N COLUMNS, EVERY ORDER OF'
'1 TO N ONCE. IT IS BUILT UP FROM PERMS 1: EACH NEW NUMBER K'
'IS PUT INTO EVERY PERMUTATION OF 1 TO K-1 AT EVERY ONE OF'
'ITS K POSITIONS. THE ROWS COME OUT GROUPED BY THAT POSITION,'
'NOT IN DICTIONARY ORDER; PERMS 5 HAS 120 ROWS, PERMS 7 5040,'
'AND THE WORKSPACE WILL NOT HOLD MANY MORE.'
∇
∇HOWCOMBS
'K COMBS N IS A MATRIX OF K!N ROWS AND K COLUMNS, EVERY WAY OF'
'CHOOSING K OF 1 TO N ONCE, EACH ROW ASCENDING AND THE ROWS IN'
'DICTIONARY ORDER. IT IS MADE FROM THE 2*N ROWS OF N BINARY'
'DIGITS, KEEPING THOSE WITH K ONES, SO N BEYOND 12 OR SO IS'
'SLOW AND LARGE.'
∇
∇HOWBASE
'B BASE N IS THE DIGITS OF N IN BASE B, MOST SIGNIFICANT'
'FIRST, AS MANY AS N NEEDS; B UNBASE D TURNS THEM BACK. THEY'
'ARE ENCODE AND DECODE, ⊤ AND ⊥, WITH THE NUMBER OF DIGITS'
'WORKED OUT FOR YOU. DIGITS N IS 10 BASE N.'
''
'      2 BASE 13'
'1 1 0 1'
'      2 UNBASE 1 1 0 1'
'13'
∇
∇R←PRIMES N
⍝ THE SIEVE AS ONE EXPRESSION: A NUMBER IS PRIME WHEN EXACTLY TWO
⍝ OF 1 TO N DIVIDE IT. THE TABLE IS N BY N, SO N IN THE HUNDREDS.
R←(2=+⌿0=(⍳N)∘.|⍳N)/⍳N
∇
∇R←ISPRIME N
R←2=+/0=(⍳N)|N
∇
∇R←FACTORS N;D
⍝ TRIAL DIVISION FROM 2, EACH FACTOR TAKEN OUT AS OFTEN AS IT GOES.
R←⍳0
D←2
L:→(N=1)/0
→(0≠D|N)/NEXT
R←R,D
N←N÷D
→L
NEXT:D←D+1
→L
∇
∇R←DIVISORS N
R←(0=(⍳N)|N)/⍳N
∇
∇R←A GCD B;T
⍝ EUCLID: REPLACE THE PAIR BY THE SMALLER AND THE REMAINDER.
L:→(B=0)/END
T←B
B←B|A
A←T
→L
END:R←A
∇
∇R←A LCM B
R←(A×B)÷A GCD B
∇
∇R←TOTIENT N;P
⍝ EULER'S FORMULA: N TIMES THE PRODUCT OVER ITS DISTINCT PRIME
⍝ FACTORS P OF 1-1÷P. TOTIENT 1 IS 1, THE EMPTY PRODUCT.
P←FACTORS N
P←((⍳⍴P)=P⍳P)/P
R←N××/1-÷P
∇
∇R←FIB N
R←1 1
L:→((⍴R)≥N)/END
R←R,+/¯2↑R
→L
END:R←N↑R
∇
∇R←PASCAL N
⍝ ROW I, COLUMN J IS (J-1)!(I-1); A ZERO ABOVE THE DIAGONAL.
R←⍉(0,⍳N)∘.!0,⍳N
∇
∇R←PERMS N;K;I;M
⍝ FROM THE ONE PERMUTATION OF 1, PUT EACH NEW K INTO EVERY ROW AT
⍝ EVERY POSITION. HOWPERMS.
R←1 1⍴1
K←1
NEXT:→(K≥N)/0
K←K+1
M←(0,K)⍴0
I←0
POS:→(I≥K)/DONE
I←I+1
M←M,[1](R[;⍳I-1],K),R[;(I-1)+⍳K-I]
→POS
DONE:R←M
→NEXT
∇
∇R←K COMBS N;B
⍝ THE BINARY ROWS WITH K ONES, LARGEST NUMBER FIRST SO THAT THE
⍝ SUBSETS COME IN DICTIONARY ORDER, EACH ROW TURNED INTO THE
⍝ POSITIONS OF ITS ONES. HOWCOMBS.
B←⍉(N⍴2)⊤⌽¯1+⍳2*N
B←(K=+/B)⌿B
R←((⍴B)[1],K)⍴(,B)/,(⍴B)⍴⍳N
∇
∇R←B BASE N
⍝ AS MANY DIGITS AS N NEEDS: 1+⌊B⍟N, AND ONE FOR 0.
R←((1+⌊B⍟N⌈1)⍴B)⊤N
∇
∇R←B UNBASE D
R←B⊥D
∇
∇R←DIGITS N
R←10 BASE N
∇
∇R←ROMAN N;V;S;I
⍝ GREEDY: TAKE THE LARGEST VALUE THAT FITS, ITS SYMBOL OR PAIR OF
⍝ SYMBOLS, AND GO ON WITH THE REST.
V←1000 900 500 400 100 90 50 40 10 9 5 4 1
S←13 2⍴'M CMD CDC XCL XLX IXV IVI '
R←''
I←1
L:→(N=0)/0
→(N<V[I])/NEXT
R←R,(S[I;]≠' ')/S[I;]
N←N-V[I]
→L
NEXT:I←I+1
→L
∇
∇R←COLLATZ N
R←N
L:→(N=1)/0
N←((N÷2)×0=2|N)+(1+3×N)×2|N
R←R,N
→L
∇
