⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 17.00.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID MATRIX
∇DESCRIBE
'MATRIX -- LINEAR ALGEBRA, MOSTLY OVER DOMINO.'
''
'   ID N          THE N BY N IDENTITY.'
'   DET M         THE DETERMINANT, BY ELIMINATION.'
'   INV M         THE INVERSE: DOMINO.'
'   A SOLVE B     X WITH A+.×X EQUAL TO B: DOMINO.'
'   TRACE M       THE SUM OF THE DIAGONAL.'
'   M MPOW N      M TO THE POWER N BY MATRIX PRODUCT.'
'   NORM V        THE EUCLIDEAN LENGTH OF A VECTOR, OR OF ALL'
'                 THE ELEMENTS OF A MATRIX.'
'   ISSYM M       1 IF M IS SQUARE AND EQUAL TO ITS TRANSPOSE.'
'   GRAM M        THE COLUMNS OF M MADE ORTHONORMAL.'
''
'TYPE HOWDOMINO FOR WHAT ⌹ IS, AND HOWDET AND HOWGRAM.'
∇
∇HOWDOMINO
'⌹ IS DOMINO, THE MATRIX DIVIDE. ⌹M IS THE INVERSE OF A SQUARE'
'MATRIX M, AND B⌹A SOLVES THE EQUATIONS A+.×X=B FOR X, WHICH IS'
'(⌹A)+.×B WITHOUT FORMING THE INVERSE. B MAY BE A VECTOR, OR A'
'MATRIX WITH ONE RIGHT-HAND SIDE PER COLUMN.'
''
'WHEN A HAS MORE ROWS THAN COLUMNS THE EQUATIONS CANNOT ALL'
'HOLD, AND B⌹A GIVES THE X THAT MAKES THE SUM OF SQUARED'
'ERRORS LEAST: THE LEAST SQUARES FIT, WHICH IS HOW STATS'
'FITS A LINE. A SINGULAR A IS A DOMAIN ERROR.'
''
'      ⌹2 2⍴4 7 2 6'
' 0.6 ¯0.7'
'¯0.2  0.4'
∇
∇HOWDET
'DET M WORKS THE DETERMINANT OUT BY ELIMINATION: DOWN EACH'
'COLUMN IN TURN, THE ROW WITH THE LARGEST ENTRY IS SWAPPED'
'INTO PLACE, WHICH CHANGES THE SIGN, AND MULTIPLES OF IT ARE'
'TAKEN FROM THE ROWS BELOW, WHICH DOES NOT. THE DETERMINANT'
'IS THEN THE PRODUCT DOWN THE DIAGONAL, WITH THE SIGN. A'
'COLUMN WITH NOTHING TO SWAP IN GIVES 0: THE MATRIX IS'
'SINGULAR, AND ⌹ WOULD REFUSE IT.'
∇
∇HOWGRAM
'GRAM M IS GRAM-SCHMIDT ON THE COLUMNS OF M: EACH COLUMN HAS'
'ITS COMPONENT ALONG EVERY EARLIER FINISHED COLUMN TAKEN OUT,'
'THEN IS SCALED TO LENGTH 1. THE RESULT HAS ORTHONORMAL'
'COLUMNS, SO ITS TRANSPOSE TIMES ITSELF IS THE IDENTITY.'
'COLUMNS THAT DEPEND ON EARLIER ONES COME OUT AS NOTHING'
'OVER NOTHING, A DOMAIN ERROR.'
∇
∇R←ID N
R←(⍳N)∘.=⍳N
∇
∇R←DET M;N;K;P;B;F
⍝ ELIMINATION WITH PARTIAL PIVOTING. HOWDET.
N←(⍴M)[1]
R←1
K←0
L:→(K≥N)/0
K←K+1
B←(K-1)+⍳1+N-K
P←B[(|M[B;K])⍳⌈/|M[B;K]]
→(0=M[P;K])/SING
→(P=K)/PIVOTED
M[K,P;]←M[P,K;]
R←-R
PIVOTED:R←R×M[K;K]
→(K=N)/L
B←K+⍳N-K
F←M[B;K]÷M[K;K]
M[B;]←M[B;]-F∘.×M[K;]
→L
SING:R←0
∇
∇R←INV M
R←⌹M
∇
∇R←A SOLVE B
R←B⌹A
∇
∇R←TRACE M
R←+/1 1⍉M
∇
∇R←M MPOW N
R←ID(⍴M)[1]
L:→(N≤0)/0
R←R+.×M
N←N-1
→L
∇
∇R←NORM V
R←(+/,V*2)*0.5
∇
∇R←ISSYM M
R←0
→(≠/⍴M)/0
R←∧/,M=⍉M
∇
∇R←GRAM M;J;V;I
⍝ GRAM-SCHMIDT, COLUMN BY COLUMN. HOWGRAM.
R←M
J←0
L:→(J≥(⍴M)[2])/0
J←J+1
V←M[;J]
I←0
S:→(I≥J-1)/DONE
I←I+1
V←V-R[;I]×+/R[;I]×V
→S
DONE:R[;J]←V÷(+/V*2)*0.5
→L
∇
