⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 17.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID PLOT
HEIGHT←15
∇DESCRIBE
'PLOT -- PICTURES IN CHARACTERS, 64 COLUMNS WIDE.'
''
'   PLOT Y        Y AGAINST ITS POSITION, POINTS JOINED.'
'   X GRAPH Y     Y AGAINST X, POINTS JOINED IN ORDER OF X.'
'   X SCATTER Y   Y AGAINST X, POINTS ALONE.'
'   BAR V         A HORIZONTAL BAR PER ELEMENT OF V.'
''
'THE LEAST AND GREATEST OF EACH AXIS ARE PRINTED ABOVE AND'
'BELOW THE PICTURE, WHICH IS HEIGHT ROWS TALL: SET HEIGHT TO'
'CHANGE IT. TYPE HOWPLOT FOR MORE.'
∇
∇HOWPLOT
'A PICTURE IS A MATRIX OF BLANKS AND STARS, 60 WIDE AND HEIGHT'
'TALL, WITH AN AXIS DOWN THE LEFT AND ALONG THE BOTTOM. EACH'
'POINT GOES TO THE COLUMN NEAREST ITS X, THE LEAST X AT THE'
'LEFT AND THE GREATEST AT THE RIGHT, AND TO THE ROW NEAREST'
'ITS Y, THE GREATEST Y AT THE TOP. PLOT AND GRAPH THEN FILL THE'
'ROWS BETWEEN EACH POINT AND THE NEXT, SO A CURVE IS JOINED;'
'SCATTER LEAVES THE POINTS ALONE. THE NUMBERS ON THE AXES ARE'
'PRINTED AS LINES OF TEXT, SINCE THIS APL HAS NO WAY TO WRITE'
'THEM INTO THE PICTURE.'
''
'      PLOT 1○(⍳60)÷10'
''
'DRAWS A SINE WAVE OVER SIX RADIANS; PLOT (⍳15)*2 A PARABOLA.'
'BAR V SCALES THE LARGEST BAR TO 58 STARS.'
∇
∇PLOT Y
(⍳×/⍴Y) GRAPH ,Y
∇
∇X GRAPH Y;∆JOIN
∆JOIN←1
X ∆PIC Y
∇
∇X SCATTER Y;∆JOIN
∆JOIN←0
X ∆PIC Y
∇
∇X ∆PIC Y;W;H;XL;XH;YL;YH;C;R;V;O;K;A;B
⍝ THE PICTURE: COLUMNS FROM X, ROWS FROM Y, A STAR AT EACH POINT,
⍝ THE ROWS BETWEEN ONE POINT AND THE NEXT FILLED IF THE CALLER'S
⍝ ∆JOIN SAYS SO. AN AXIS OF ONE VALUE IS GIVEN A RANGE OF ONE, SO
⍝ NOTHING IS DIVIDED BY ZERO. HOWPLOT.
X←,X
Y←,Y
W←60
H←HEIGHT
XL←⌊/X
XH←⌈/X
YL←⌊/Y
YH←⌈/Y
C←1+⌊0.5+(W-1)×(X-XL)÷(XH-XL)⌈XL=XH
R←H-⌊0.5+(H-1)×(Y-YL)÷(YH-YL)⌈YL=YH
V←(H×W)⍴' '
→(~∆JOIN)/MARK
O←⍋X
C←C[O]
R←R[O]
K←1
J:→(K≥⍴C)/MARK
K←K+1
A←R[K-1]⌊R[K]
B←R[K-1]⌈R[K]
V[C[K]+W×(A-2)+⍳1+B-A]←'*'
→J
MARK:V[C+W×R-1]←'*'
'Y FROM ';YL;' TO ';YH
('|',(H,W)⍴V),[1]'+',W⍴'-'
'X FROM ';XL;' TO ';XH
∇
∇BAR V;L
⍝ ONE ROW PER ELEMENT, THE LARGEST SCALED TO 58 STARS; A NEGATIVE
⍝ VALUE DRAWS NOTHING.
V←0⌈,V
L←⌊0.5+58×V÷(⌈/V)⌈0=⌈/V
'BARS FROM 0 TO ';⌈/V
'|',' *'[1+L∘.≥⍳58]
∇
