⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 17.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID POLY
∇DESCRIBE
'POLY -- POLYNOMIALS AS VECTORS OF COEFFICIENTS, HIGHEST POWER'
'FIRST: 1 ¯3 2 IS X*2 LESS 3X PLUS 2.'
''
'   P PEVAL X     P AT X, A NUMBER OR A VECTOR OF THEM.'
'   P PADD Q      THE SUM.'
'   P PMUL Q      THE PRODUCT.'
'   P PDIV Q      THE QUOTIENT OF P BY Q.'
'   P PREM Q      THE REMAINDER.'
'   PDERIV P      THE DERIVATIVE.'
'   PINT P        THE INTEGRAL, WITH CONSTANT 0.'
'   PROOTS P      THE REAL ROOTS.'
'   PSHOW P       P WRITTEN OUT, AS CHARACTERS.'
''
'TYPE HOWPOLY FOR MORE.'
∇
∇HOWPOLY
'HIGHEST POWER FIRST IS THE ORDER DECODE WANTS: X⊥P EVALUATES'
'P AT X BY HORNER''S RULE, AND THAT IS WHAT PEVAL DOES, FOR A'
'VECTOR OF X BY AN OUTER PRODUCT OF POWERS. A LEADING ZERO IS'
'HARMLESS; RESULTS COME BACK WITHOUT ONE, AND A ZERO'
'POLYNOMIAL IS ,0.'
''
'PMUL IS THE OUTER PRODUCT OF THE COEFFICIENTS SUMMED ALONG'
'ITS DIAGONALS. PDIV AND PREM ARE LONG DIVISION. PROOTS RUNS'
'NEWTON''S METHOD FROM FORTY-ONE STARTS SPREAD OVER THE RANGE'
'THE ROOTS MUST LIE IN, KEEPS WHAT CONVERGED, AND GIVES EACH'
'ROOT ONCE, TO SIX PLACES, ASCENDING: IT FINDS REAL ROOTS,'
'A REPEATED ROOT ONCE AND ONLY ROUGHLY, SINCE THE VALUE OF THE'
'POLYNOMIAL BESIDE IT IS LOST TO ROUNDING, AND NO COMPLEX'
'ONES, SO X*2+1 GIVES AN EMPTY VECTOR. PSHOW WRITES WHOLE'
'COEFFICIENTS EXACTLY AND OTHERS TO THREE PLACES.'
''
'      PSHOW 2 0 ¯3 1'
'2X*3-3X+1'
∇
∇R←P PEVAL X
R←(X∘.*⌽¯1+⍳⍴P←,P)+.×P
∇
∇R←∆TRIM P
⍝ WITHOUT ITS LEADING ZEROS; A POLYNOMIAL OF NOTHING IS ,0.
R←(∨\0≠P←,P)/P
→(0<⍴R)/0
R←,0
∇
∇R←P PADD Q;M
M←(⍴P←,P)⌈⍴Q←,Q
R←∆TRIM((-M)↑P)+(-M)↑Q
∇
∇R←P PMUL Q;N
⍝ THE OUTER PRODUCT SUMMED ALONG ITS DIAGONALS: TERM K OF THE
⍝ RESULT COLLECTS EVERY PAIR WHOSE POSITIONS ADD TO K+1.
N←¯1+(⍴P←,P)+⍴Q←,Q
R←∆TRIM((⍳N)∘.=,¯1+(⍳⍴P)∘.+⍳⍴Q)+.×,P∘.×Q
∇
∇∆LDIV;C
⍝ LONG DIVISION OF THE CALLER'S P BY ITS Q, LEAVING THE QUOTIENT
⍝ IN ∆Q AND THE REMAINDER IN P.
P←∆TRIM P
Q←∆TRIM Q
∆Q←⍳0
L:→((⍴P)<⍴Q)/0
C←P[1]÷Q[1]
∆Q←∆Q,C
P←1↓P-(C×Q),((⍴P)-⍴Q)⍴0
→L
∇
∇R←P PDIV Q;∆Q
∆LDIV
R←∆TRIM ∆Q
∇
∇R←P PREM Q;∆Q
∆LDIV
R←∆TRIM P
∇
∇R←PDERIV P
R←∆TRIM(¯1↓P←,P)×⌽⍳¯1+⍴P
∇
∇R←PINT P
R←(P÷⌽⍳⍴P←,P),0
∇
∇R←PROOTS P;B;X;D;K
⍝ NEWTON FROM FORTY-ONE STARTS ACROSS THE CAUCHY BOUND, FIFTY
⍝ STEPS AT ONCE FOR ALL OF THEM; A ZERO DERIVATIVE IS NUDGED. WHAT
⍝ CONVERGED IS ROUNDED TO SIX PLACES, WHICH IS ALL A REPEATED ROOT
⍝ CAN GIVE IN THIS ARITHMETIC, AND VALUES WITHIN 1E¯5 ARE ONE ROOT.
P←∆TRIM P
B←1+⌈/|(1↓P)÷P[1]
X←B×(¯21+⍳41)÷20
D←PDERIV P
K←0
L:→(K≥50)/DONE
K←K+1
X←X-(P PEVAL X)÷(D PEVAL X)+1E¯12×0=D PEVAL X
→L
DONE:X←(1E¯8>|P PEVAL X)/X
X←(⌊0.5+X×1E6)÷1E6
X←X[⍋X]
R←(1,1E¯5<|1↓X-¯1⌽X)/X
∇
∇R←PSHOW P;N;K;C;E
⍝ EACH TERM WITH A COEFFICIENT: SIGN, THE COEFFICIENT UNLESS IT IS
⍝ 1 AND THERE IS AN X, THEN X AND ITS POWER WHERE THEY APPLY.
P←∆TRIM P
N←×/⍴P
R←''
K←0
L:→(K≥N)/END
K←K+1
C←P[K]
E←N-K
→(C=0)/L
→((C<0)∨0=⍴R)/SIGNED
R←R,'+'
SIGNED:R←R,(C<0)/'-'
→((1=|C)∧E>0)/POWER
R←R,∆NUM|C
POWER:→(E=0)/L
R←R,'X'
→(E=1)/L
R←R,'*',∆NUM E
→L
END:→(0<⍴R)/0
R←,'0'
∇
∇R←∆NUM X;I;F
⍝ A NON-NEGATIVE NUMBER AS CHARACTERS WITHOUT FORMAT: THE WHOLE
⍝ PART BY ENCODE, AND UP TO THREE DECIMALS.
I←⌊X
F←⌊0.5+1000×X-I
→(F<1000)/SPLIT
I←I+1
F←0
SPLIT:R←'0123456789'[1+((1+⌊10⍟I⌈1)⍴10)⊤I]
→(F=0)/0
F←(3⍴10)⊤F
R←R,'.',(⌽∨\⌽0≠F)/'0123456789'[1+F]
∇
