⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 20.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID POLY
∇DESCRIBE
'POLY -- POLYNOMIALS AS VECTORS OF COEFFICIENTS, HIGHEST POWER'
'FIRST: 1 ¯3 2 IS X*2 LESS 3X PLUS 2.'
''
'   P PEVAL X     P AT X, A NUMBER OR A VECTOR OF THEM.'
'   P PADD Q      THE SUM.'
'   P PMUL Q      THE PRODUCT.'
'   P PDIV Q      THE QUOTIENT OF P BY Q.'
'   P PREM Q      THE REMAINDER.'
'   PDERIV P      THE DERIVATIVE.'
'   PINT P        THE INTEGRAL, WITH CONSTANT 0.'
'   PROOTS P      THE REAL ROOTS.'
'   PSHOW P       P WRITTEN OUT, AS CHARACTERS.'
''
'TYPE HOWPOLY FOR MORE.'
∇
∇HOWPOLY
'HIGHEST POWER FIRST IS THE ORDER DECODE WANTS: X⊥P EVALUATES'
'P AT X BY HORNER''S RULE, AND THAT IS WHAT PEVAL DOES, FOR A'
'VECTOR OF X BY AN OUTER PRODUCT OF POWERS. A LEADING ZERO IS'
'HARMLESS; RESULTS COME BACK WITHOUT ONE, AND A ZERO'
'POLYNOMIAL IS ,0.'
''
'PMUL IS THE OUTER PRODUCT OF THE COEFFICIENTS SUMMED ALONG'
'ITS DIAGONALS. PDIV AND PREM ARE LONG DIVISION. PROOTS'
'SAMPLES THE POLYNOMIAL AT 401 POINTS ACROSS THE RANGE THE'
'ROOTS MUST LIE IN, BISECTS EVERY SIGN CHANGE, AND RUNS'
'NEWTON''S METHOD FROM EVERY POINT FOR A ROOT THAT TOUCHES'
'WITHOUT CROSSING; IT GIVES EACH ROOT ONCE, TO SIX PLACES,'
'ASCENDING. ROOTS CLOSER THAN 1E¯3 ARE TAKEN AS ONE, AND A'
'REPEATED ROOT IS FOUND ONLY ROUGHLY, SINCE THE VALUE OF THE'
'POLYNOMIAL BESIDE IT IS LOST TO ROUNDING; NO COMPLEX ROOTS,'
'SO X*2+1 GIVES AN EMPTY VECTOR. PSHOW WRITES WHOLE'
'COEFFICIENTS EXACTLY AND OTHERS TO THREE PLACES.'
''
'      PSHOW 2 0 ¯3 1'
'2X*3-3X+1'
∇
∇R←P PEVAL X
⍝ RAVELLED FIRST, ON ITS OWN LINE: A LINE IS READ FROM THE RIGHT, SO
⍝ AN ASSIGNMENT IN IT WOULD NOT REACH A USE TO ITS RIGHT.
P←,P
R←(X∘.*⌽¯1+⍳⍴P)+.×P
∇
∇R←∆TRIM P
⍝ WITHOUT ITS LEADING ZEROS; A POLYNOMIAL OF NOTHING IS ,0.
R←(∨\0≠P←,P)/P
→(0<⍴R)/0
R←,0
∇
∇R←P PADD Q;M
M←(⍴P←,P)⌈⍴Q←,Q
R←∆TRIM((-M)↑P)+(-M)↑Q
∇
∇R←P PMUL Q;N
⍝ THE OUTER PRODUCT SUMMED ALONG ITS DIAGONALS: TERM K OF THE
⍝ RESULT COLLECTS EVERY PAIR WHOSE POSITIONS ADD TO K+1.
N←¯1+(⍴P←,P)+⍴Q←,Q
R←∆TRIM((⍳N)∘.=,¯1+(⍳⍴P)∘.+⍳⍴Q)+.×,P∘.×Q
∇
∇∆LDIV;C
⍝ LONG DIVISION OF THE CALLER'S P BY ITS Q, LEAVING THE QUOTIENT
⍝ IN ∆Q AND THE REMAINDER IN P.
P←∆TRIM P
Q←∆TRIM Q
∆Q←⍳0
L:→((⍴P)<⍴Q)/0
C←P[1]÷Q[1]
∆Q←∆Q,C
P←1↓P-(C×Q),((⍴P)-⍴Q)⍴0
→L
∇
∇R←P PDIV Q;∆Q
∆LDIV
R←∆TRIM ∆Q
∇
∇R←P PREM Q;∆Q
∆LDIV
R←∆TRIM P
∇
∇R←PDERIV P
P←,P
R←∆TRIM(¯1↓P)×⌽⍳¯1+⍴P
∇
∇R←PINT P
P←,P
R←(P÷⌽⍳⍴P),0
∇
∇R←PROOTS P;B;X;Y;C;LO;HI;M;K;D;Z;S;G
⍝ EVERY REAL ROOT LIES WITHIN THE CAUCHY BOUND B. THE POLYNOMIAL IS
⍝ SAMPLED AT 401 POINTS ACROSS ¯B TO B; A ROOT ON A POINT IS TAKEN,
⍝ AND EACH SIGN CHANGE BETWEEN NEIGHBOURS IS BISECTED SIXTY TIMES,
⍝ ALL BRACKETS AT ONCE. A ROOT THAT TOUCHES WITHOUT CROSSING SHOWS
⍝ NO SIGN CHANGE, SO NEWTON RUNS FROM EVERY POINT AS WELL, FIFTY
⍝ STEPS, AND A POINT WHOSE LAST STEP WAS UNDER 1E¯7 IS KEPT. VALUES
⍝ WITHIN 1E¯3 OF THEIR NEIGHBOUR ARE ONE ROOT, AT THEIR MEAN -- A
⍝ REPEATED ROOT IS A PLATEAU THAT WIDE WHERE THE POLYNOMIAL COMPUTES
⍝ AS ZERO -- AND EACH IS ROUNDED TO SIX PLACES. HOWPOLY.
P←∆TRIM P
B←1+⌈/|(1↓P)÷P[1]
X←B×(¯201+⍳401)÷200
Y←P PEVAL X
R←(0=Y)/X
C←0>(1↓×Y)×¯1↓×Y
LO←C/¯1↓X
HI←C/1↓X
K←0
BIS:→(K≥60)/NEWT
K←K+1
M←(LO+HI)÷2
Z←(×P PEVAL M)=×P PEVAL LO
LO←(Z×M)+(~Z)×LO
HI←(Z×HI)+(~Z)×M
→BIS
NEWT:R←R,(LO+HI)÷2
D←PDERIV P
Z←X
K←0
NL:→(K≥50)/DONE
K←K+1
S←(P PEVAL Z)÷(D PEVAL Z)+1E¯12×0=D PEVAL Z
Z←Z-S
→NL
DONE:R←R,(1E¯7>|S)/Z
→(0=⍴R)/0
R←R[⍋R]
G←1,1E¯3<|1↓R-¯1⌽R
M←(⍳+/G)∘.=+\G
R←(⌊0.5+1E6×(M+.×R)÷+/M)÷1E6
∇
∇R←PSHOW P;N;K;C;E
⍝ EACH TERM WITH A COEFFICIENT: SIGN, THE COEFFICIENT UNLESS IT IS
⍝ 1 AND THERE IS AN X, THEN X AND ITS POWER WHERE THEY APPLY.
P←∆TRIM P
N←×/⍴P
R←''
K←0
L:→(K≥N)/END
K←K+1
C←P[K]
E←N-K
→(C=0)/L
→((C<0)∨0=⍴R)/SIGNED
R←R,'+'
SIGNED:R←R,(C<0)/'-'
→((1=|C)∧E>0)/POWER
R←R,∆NUM|C
POWER:→(E=0)/L
R←R,'X'
→(E=1)/L
R←R,'*',∆NUM E
→L
END:→(0<⍴R)/0
R←,'0'
∇
∇R←∆NUM X;I;F
⍝ A NON-NEGATIVE NUMBER AS CHARACTERS WITHOUT FORMAT: THE WHOLE
⍝ PART BY ENCODE, AND UP TO THREE DECIMALS.
I←⌊X
F←⌊0.5+1000×X-I
→(F<1000)/SPLIT
I←I+1
F←0
SPLIT:R←'0123456789'[1+((1+⌊10⍟I⌈1)⍴10)⊤I]
→(F=0)/0
F←(3⍴10)⊤F
R←R,'.',(⌽∨\⌽0≠F)/'0123456789'[1+F]
∇
