⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 18.00.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID STATS
∇DESCRIBE
'STATS -- STATISTICS ON NUMERIC VECTORS.'
''
'   MEAN V        THE AVERAGE.'
'   MEDIAN V      THE MIDDLE VALUE, OR THE MEAN OF THE TWO.'
'   MODE V        THE MOST FREQUENT VALUE, OR VALUES.'
'   RANGE V       THE GREATEST LESS THE LEAST.'
'   VAR V, SD V   SAMPLE VARIANCE AND STANDARD DEVIATION.'
'   PVAR V, PSD V THE SAME FOR A WHOLE POPULATION.'
'   P QUANTILE V  THE VALUE A FRACTION P OF THE WAY UP.'
'   SUMMARY V     LEAST, QUARTILES, MEDIAN, GREATEST, MEAN, SD.'
'   ZSCORE V      EACH VALUE IN STANDARD DEVIATIONS FROM MEAN.'
'   RANK V        THE RANK OF EACH VALUE, TIES AVERAGED.'
'   FREQ V        DISTINCT VALUES AND THEIR COUNTS.'
'   N HIST V      A HISTOGRAM IN N BINS.'
''
'ON TWO VARIABLES, X AND Y OF ONE LENGTH:'
''
'   X COV Y       SAMPLE COVARIANCE.'
'   X CORR Y      CORRELATION.'
'   X REGRESS Y   LEAST SQUARES: THE INTERCEPT, THEN A SLOPE'
'                 PER COLUMN OF X, A VECTOR OR A MATRIX.'
'   X RESID Y     Y LESS THE FITTED LINE.'
'   X RSQ Y       THE FRACTION OF THE VARIANCE THE FIT EXPLAINS.'
'   B PREDICT X   THE LINE B AT NEW X.'
''
'TESTS, EACH GIVING THE STATISTIC AND ITS DEGREES OF FREEDOM:'
''
'   M TTEST1 V    ONE SAMPLE AGAINST A MEAN M.'
'   X TTEST2 Y    TWO SAMPLES, VARIANCES POOLED.'
'   CHISQ T       A CONTINGENCY TABLE T, ROWS BY COLUMNS.'
'   NORMAL Z      THE STANDARD NORMAL DISTRIBUTION AT Z.'
'   PNORM Z       THE TWO-SIDED PROBABILITY OF A Z THAT LARGE.'
''
'RANDOM, FROM THE WORKSPACE''S OWN SEQUENCE:'
''
'   RANDU N       N UNIFORM ON 0 TO 1.'
'   A RANDIN N    N UNIFORM ON A[1] TO A[2].'
'   RANDN N       N STANDARD NORMAL.'
'   N SAMPLE V    N OF V WITHOUT REPLACEMENT.'
'   SHUFFLE V     V IN A RANDOM ORDER.'
''
'A MATRIX GIVEN TO A ONE-VARIABLE FUNCTION IS TAKEN AS THE'
'VECTOR OF ALL ITS ELEMENTS. TYPE HOWQUANTILE, HOWRANK,'
'HOWHIST, HOWSUMMARY, HOWREGRESS, HOWTEST OR HOWRANDOM.'
∇
∇HOWQUANTILE
'P QUANTILE V IS THE VALUE A FRACTION P OF THE WAY UP THE'
'SORTED VECTOR, BY LINEAR INTERPOLATION: THE POSITION IS'
'1+P×N-1, AND A POSITION BETWEEN TWO VALUES TAKES ITS SHARE'
'OF EACH. P MAY BE A VECTOR. 0 AND 1 GIVE THE LEAST AND THE'
'GREATEST, 0.5 THE MEDIAN, 0.25 0.75 THE QUARTILES.'
''
'      0.25 0.5 0.75 QUANTILE 2 4 4 4 5 5 7 9'
'4 4.5 5.5'
∇
∇HOWRANK
'RANK V GIVES EACH VALUE ITS PLACE IN ASCENDING ORDER, 1 FOR'
'THE LEAST. VALUES THAT TIE SHARE THE MEAN OF THE PLACES THEY'
'WOULD HAVE TAKEN, SO THE RANKS STILL SUM TO 1+2+...+N.'
''
'      RANK 2 4 4 4 5 5 7 9'
'1 3 3 3 5.5 5.5 7 8'
∇
∇HOWHIST
'N HIST V DIVIDES THE RANGE OF V INTO N BINS OF EQUAL WIDTH'
'AND PRINTS THE BIN EDGES, THEN ONE ROW OF STARS PER BIN, THE'
'LOWEST BIN FIRST. A VALUE ON AN EDGE GOES IN THE BIN ABOVE'
'IT, EXCEPT THE GREATEST, WHICH GOES IN THE LAST. WHEN A BIN'
'HOLDS MORE THAN 60, THE ROWS ARE SCALED AND A LINE SAYS HOW'
'MANY EACH STAR STANDS FOR.'
∇
∇HOWSUMMARY
'SUMMARY V PRINTS SEVEN LINES: THE LEAST, THE LOWER QUARTILE,'
'THE MEDIAN, THE UPPER QUARTILE, THE GREATEST, THE MEAN AND'
'THE SAMPLE STANDARD DEVIATION. THE QUARTILES ARE QUANTILE AT'
'0.25 AND 0.75.'
∇
∇R←MEAN V
R←(+/,V)÷×/⍴V
∇
∇R←MEDIAN V;S;N
S←V[⍋V←,V]
N←×/⍴V
R←0.5×S[⌈N÷2]+S[⌊1+N÷2]
∇
∇R←MODE V;C
⍝ EVERY VALUE THAT OCCURS AS OFTEN AS THE MOST FREQUENT, EACH ONCE,
⍝ IN THE ORDER FIRST MET.
V←,V
C←+/V∘.=V
R←(C=⌈/C)/V
R←((⍳⍴R)=R⍳R)/R
∇
∇R←RANGE V
R←(⌈/,V)-⌊/,V
∇
∇R←VAR V
⍝ SAMPLE VARIANCE: THE SUM OF SQUARED DEVIATIONS OVER N-1.
R←(+/(,V-MEAN V)*2)÷¯1+×/⍴V
∇
∇R←SD V
R←(VAR V)*0.5
∇
∇R←PVAR V
⍝ POPULATION VARIANCE: OVER N.
R←(+/(,V-MEAN V)*2)÷×/⍴V
∇
∇R←PSD V
R←(PVAR V)*0.5
∇
∇R←P QUANTILE V;S;H;N
⍝ THE VALUE A FRACTION P OF THE WAY UP THE SORTED VECTOR, BETWEEN
⍝ TWO VALUES BY THEIR SHARE. HOWQUANTILE.
S←V[⍋V←,V]
N←×/⍴V
H←1+P×N-1
R←S[⌊H]+(H-⌊H)×S[⌈H]-S[⌊H]
∇
∇SUMMARY V
V←,V
'LEAST          ';⌊/V
'LOWER QUARTILE ';0.25 QUANTILE V
'MEDIAN         ';MEDIAN V
'UPPER QUARTILE ';0.75 QUANTILE V
'GREATEST       ';⌈/V
'MEAN           ';MEAN V
'SD             ';SD V
∇
∇R←ZSCORE V
R←(V-MEAN V)÷SD V
∇
∇R←RANK V;E;O;N
⍝ THE PLACE OF EACH VALUE IN ASCENDING ORDER; TIES SHARE THE MEAN OF
⍝ THEIR PLACES. E IS WHICH VALUES ARE EQUAL, O THE PLACES WITHOUT
⍝ TIES. HOWRANK.
V←,V
N←×/⍴V
O←⍋⍋V
E←V∘.=V
R←(+/E×(N,N)⍴O)÷+/E
∇
∇R←FREQ V;U
⍝ THE DISTINCT VALUES IN ASCENDING ORDER, AND HOW OFTEN EACH OCCURS:
⍝ A MATRIX OF TWO COLUMNS.
V←,V
U←((⍳⍴V)=V⍳V)/V
U←U[⍋U]
R←⍉(2,⍴U)⍴U,+/U∘.=V
∇
∇N HIST V;L;H;W;B;C;M;S
⍝ N BINS OF EQUAL WIDTH FROM THE LEAST TO THE GREATEST; A VALUE ON
⍝ AN EDGE GOES IN THE BIN ABOVE, THE GREATEST IN THE LAST. ROWS OF
⍝ STARS, SCALED TO 60 WHEN A COUNT IS LARGER. HOWHIST.
V←,V
L←⌊/V
H←⌈/V
→(L<H)/SPREAD
N←1
H←L+1
SPREAD:W←(H-L)÷N
'BIN EDGES: ';L+W×¯1+⍳N+1
B←1⌈N⌊⌈(V-L)÷W
C←+/(⍳N)∘.=B
M←⌈/C
S←1
→(M≤60)/DRAW
S←M÷60
'EACH * IS ';S
DRAW:C←⌊0.5+C÷S
' *'[1+C∘.≥⍳1⌈⌈/C]
∇
∇HOWREGRESS
'X REGRESS Y FITS Y TO X BY LEAST SQUARES, USING DOMINO ON A'
'MATRIX WHOSE FIRST COLUMN IS ONES: THE RESULT IS THE'
'INTERCEPT, THEN ONE COEFFICIENT PER COLUMN OF X. X MAY BE A'
'VECTOR, ONE REGRESSOR, OR A MATRIX WITH A REGRESSOR IN EACH'
'COLUMN AND A ROW PER OBSERVATION.'
''
'      1 2 3 4 5 REGRESS 2 4 5 4 5'
'2.2 0.6'
''
'X RESID Y IS Y LESS THE FIT, X RSQ Y THE SHARE OF THE'
'VARIANCE OF Y THE FIT ACCOUNTS FOR, AND B PREDICT X THE FIT'
'AT ANY X FOR THE COEFFICIENTS B THAT REGRESS GAVE. AN EXACT'
'FIT LEAVES RESIDUALS OF THE ORDER OF 1E¯15, THE ARITHMETIC''S'
'ROUNDING, NOT ZEROS.'
∇
∇R←X COV Y
⍝ SAMPLE COVARIANCE, OVER N-1.
R←(+/(,X-MEAN X)×,Y-MEAN Y)÷¯1+×/⍴X
∇
∇R←X CORR Y
R←(X COV Y)÷(SD X)×SD Y
∇
∇R←∆DESIGN X
⍝ THE MATRIX LEAST SQUARES WORKS ON: A COLUMN OF ONES, THEN X AS
⍝ A COLUMN, OR ITS COLUMNS IF IT IS A MATRIX.
→(2=⍴⍴X)/MAT
X←((×/⍴X),1)⍴X
MAT:R←1,X
∇
∇R←X REGRESS Y
⍝ THE INTERCEPT AND THE COEFFICIENTS, BY DOMINO. HOWREGRESS.
R←(,Y)⌹∆DESIGN X
∇
∇R←X RESID Y
R←(,Y)-(∆DESIGN X)+.×X REGRESS Y
∇
∇R←X RSQ Y
⍝ ONE LESS THE RESIDUAL SUM OF SQUARES OVER THE TOTAL.
R←1-(+/(X RESID Y)*2)÷+/(,Y-MEAN Y)*2
∇
∇R←B PREDICT X
R←(∆DESIGN X)+.×B
∇
∇HOWTEST
'EACH TEST GIVES TWO NUMBERS: THE STATISTIC, AND THE DEGREES'
'OF FREEDOM TO READ IT WITH.'
''
'M TTEST1 V: T IS THE MEAN OF V LESS M, OVER THE SAMPLE SD'
'OVER THE ROOT OF N; N-1 DEGREES OF FREEDOM.'
''
'X TTEST2 Y: T IS THE DIFFERENCE OF THE MEANS OVER THE POOLED'
'SD TIMES THE ROOT OF 1÷N1 PLUS 1÷N2, THE POOLED VARIANCE'
'BEING THE WEIGHTED MEAN OF THE TWO SAMPLE VARIANCES; N1+N2-2'
'DEGREES OF FREEDOM.'
''
'CHISQ T: THE EXPECTED COUNT IN EACH CELL IS ITS ROW TOTAL'
'TIMES ITS COLUMN TOTAL OVER THE GRAND TOTAL, AND THE'
'STATISTIC IS THE SUM OF (OBSERVED-EXPECTED)*2 OVER EXPECTED;'
'(ROWS-1)×(COLUMNS-1) DEGREES OF FREEDOM.'
''
'NORMAL Z IS THE PROBABILITY THAT A STANDARD NORMAL VALUE IS'
'BELOW Z, GOOD TO SEVEN PLACES; PNORM Z IS 2×1-NORMAL |Z, THE'
'TWO-SIDED PROBABILITY. THERE IS NO T DISTRIBUTION HERE: WITH'
'THIRTY OR MORE DEGREES OF FREEDOM READ T AGAINST THE NORMAL,'
'AND WITH FEWER USE A TABLE.'
∇
∇HOWRANDOM
'THE RANDOM FUNCTIONS DRAW ON ROLL, ?, SO THEY FOLLOW THE'
'WORKSPACE''S RANDOM LINK: FROM A FRESH LOAD THEY GIVE THE'
'SAME VALUES EVERY TIME, WHICH IS WHAT MAKES A RUN REPEATABLE.'
''
'RANDU N IS N VALUES UNIFORM ON 0 TO 1, NEVER EITHER END, AND'
'A RANDIN N SCALES THEM ONTO A[1] TO A[2]. RANDN N IS N STANDARD'
'NORMAL VALUES BY THE BOX-MULLER TRANSFORM: THE ROOT OF ¯2'
'TIMES THE LOG OF ONE UNIFORM, TIMES THE COSINE OF 2 PI TIMES'
'ANOTHER. N SAMPLE V DEALS N OF V, NO ELEMENT TWICE; SHUFFLE V'
'DEALS ALL OF THEM.'
∇
∇R←M TTEST1 V;N
⍝ THE STATISTIC AND N-1. HOWTEST.
V←,V
N←×/⍴V
R←(((MEAN V)-M)÷(SD V)÷N*0.5),N-1
∇
∇R←X TTEST2 Y;N1;N2;SP
⍝ VARIANCES POOLED; THE STATISTIC AND N1+N2-2. HOWTEST.
N1←×/⍴X
N2←×/⍴Y
SP←((((N1-1)×VAR X)+(N2-1)×VAR Y)÷N1+N2-2)*0.5
R←(((MEAN X)-MEAN Y)÷SP×((÷N1)+÷N2)*0.5),N1+N2-2
∇
∇R←CHISQ T;E
⍝ A CONTINGENCY TABLE: THE STATISTIC AND (ROWS-1)×(COLUMNS-1).
E←((+/T)∘.×+⌿T)÷+/,T
R←(+/,((T-E)*2)÷E),×/¯1+⍴T
∇
∇R←NORMAL Z;T;P
⍝ THE STANDARD NORMAL DISTRIBUTION FUNCTION, BY THE RATIONAL
⍝ APPROXIMATION OF ABRAMOWITZ AND STEGUN 26.2.17, WHOSE ERROR IS
⍝ UNDER 7.5E¯8; THE NEGATIVE HALF BY SYMMETRY.
T←÷1+0.2316419×|Z
P←T×0.31938153+T×¯0.356563782+T×1.781477937+T×¯1.821255978+T×1.330274429
P←1-P×(*-0.5×Z*2)÷(○2)*0.5
R←P+(Z<0)×1-2×P
∇
∇R←PNORM Z
R←2×1-NORMAL |Z
∇
∇R←RANDU N;M
⍝ N UNIFORM ON 0 TO 1, NEVER AN END: A ROLL OF A MILLION OVER A
⍝ MILLION AND ONE.
M←1000000
R←(?N⍴M)÷M+1
∇
∇R←A RANDIN N
⍝ N UNIFORM ON A[1] TO A[2].
R←A[1]+(RANDU N)×A[2]-A[1]
∇
∇R←RANDN N
⍝ STANDARD NORMAL, BY BOX AND MULLER.
R←((¯2×⍟RANDU N)*0.5)×2○○2×RANDU N
∇
∇R←N SAMPLE V
R←(,V)[N?×/⍴V]
∇
∇R←SHUFFLE V
R←(,V)[(×/⍴V)?×/⍴V]
∇
