⍝ sw-apl workspace. Re-executable APL: loading it runs it.
⍝!MODES (A)(B)
⍝!SOURCE sw-apl-workspaces -- written for this repository. MIT, (c) 2026 Michael A Wright.
⍝!SAVED 12.30.00 09/26/26
⍝!LINK 16807
⍝!ORIGIN 1
⍝!DIGITS 10
⍝!WIDTH 64
)WSID STATS
∇DESCRIBE
'STATS -- STATISTICS ON NUMERIC VECTORS.'
''
'   MEAN V        THE AVERAGE.'
'   MEDIAN V      THE MIDDLE VALUE, OR THE MEAN OF THE TWO.'
'   MODE V        THE MOST FREQUENT VALUE, OR VALUES.'
'   RANGE V       THE GREATEST LESS THE LEAST.'
'   VAR V, SD V   SAMPLE VARIANCE AND STANDARD DEVIATION.'
'   PVAR V, PSD V THE SAME FOR A WHOLE POPULATION.'
'   P QUANTILE V  THE VALUE A FRACTION P OF THE WAY UP.'
'   SUMMARY V     LEAST, QUARTILES, MEDIAN, GREATEST, MEAN, SD.'
'   ZSCORE V      EACH VALUE IN STANDARD DEVIATIONS FROM MEAN.'
'   RANK V        THE RANK OF EACH VALUE, TIES AVERAGED.'
'   FREQ V        DISTINCT VALUES AND THEIR COUNTS.'
'   N HIST V      A HISTOGRAM IN N BINS.'
''
'A MATRIX IS TAKEN AS THE VECTOR OF ALL ITS ELEMENTS. TYPE'
'HOWQUANTILE, HOWRANK, HOWHIST OR HOWSUMMARY FOR MORE.'
∇
∇HOWQUANTILE
'P QUANTILE V IS THE VALUE A FRACTION P OF THE WAY UP THE'
'SORTED VECTOR, BY LINEAR INTERPOLATION: THE POSITION IS'
'1+P×N-1, AND A POSITION BETWEEN TWO VALUES TAKES ITS SHARE'
'OF EACH. P MAY BE A VECTOR. 0 AND 1 GIVE THE LEAST AND THE'
'GREATEST, 0.5 THE MEDIAN, 0.25 0.75 THE QUARTILES.'
''
'      0.25 0.5 0.75 QUANTILE 2 4 4 4 5 5 7 9'
'4 4.5 5.5'
∇
∇HOWRANK
'RANK V GIVES EACH VALUE ITS PLACE IN ASCENDING ORDER, 1 FOR'
'THE LEAST. VALUES THAT TIE SHARE THE MEAN OF THE PLACES THEY'
'WOULD HAVE TAKEN, SO THE RANKS STILL SUM TO 1+2+...+N.'
''
'      RANK 2 4 4 4 5 5 7 9'
'1 3 3 3 5.5 5.5 7 8'
∇
∇HOWHIST
'N HIST V DIVIDES THE RANGE OF V INTO N BINS OF EQUAL WIDTH'
'AND PRINTS THE BIN EDGES, THEN ONE ROW OF STARS PER BIN, THE'
'LOWEST BIN FIRST. A VALUE ON AN EDGE GOES IN THE BIN ABOVE'
'IT, EXCEPT THE GREATEST, WHICH GOES IN THE LAST. WHEN A BIN'
'HOLDS MORE THAN 60, THE ROWS ARE SCALED AND A LINE SAYS HOW'
'MANY EACH STAR STANDS FOR.'
∇
∇HOWSUMMARY
'SUMMARY V PRINTS SEVEN LINES: THE LEAST, THE LOWER QUARTILE,'
'THE MEDIAN, THE UPPER QUARTILE, THE GREATEST, THE MEAN AND'
'THE SAMPLE STANDARD DEVIATION. THE QUARTILES ARE QUANTILE AT'
'0.25 AND 0.75.'
∇
∇R←MEAN V
R←(+/,V)÷×/⍴V
∇
∇R←MEDIAN V;S;N
S←V[⍋V←,V]
N←×/⍴V
R←0.5×S[⌈N÷2]+S[⌊1+N÷2]
∇
∇R←MODE V;C
⍝ EVERY VALUE THAT OCCURS AS OFTEN AS THE MOST FREQUENT, EACH ONCE,
⍝ IN THE ORDER FIRST MET.
V←,V
C←+/V∘.=V
R←(C=⌈/C)/V
R←((⍳⍴R)=R⍳R)/R
∇
∇R←RANGE V
R←(⌈/,V)-⌊/,V
∇
∇R←VAR V
⍝ SAMPLE VARIANCE: THE SUM OF SQUARED DEVIATIONS OVER N-1.
R←(+/(,V-MEAN V)*2)÷¯1+×/⍴V
∇
∇R←SD V
R←(VAR V)*0.5
∇
∇R←PVAR V
⍝ POPULATION VARIANCE: OVER N.
R←(+/(,V-MEAN V)*2)÷×/⍴V
∇
∇R←PSD V
R←(PVAR V)*0.5
∇
∇R←P QUANTILE V;S;H;N
⍝ THE VALUE A FRACTION P OF THE WAY UP THE SORTED VECTOR, BETWEEN
⍝ TWO VALUES BY THEIR SHARE. HOWQUANTILE.
S←V[⍋V←,V]
N←×/⍴V
H←1+P×N-1
R←S[⌊H]+(H-⌊H)×S[⌈H]-S[⌊H]
∇
∇SUMMARY V
V←,V
'LEAST          ';⌊/V
'LOWER QUARTILE ';0.25 QUANTILE V
'MEDIAN         ';MEDIAN V
'UPPER QUARTILE ';0.75 QUANTILE V
'GREATEST       ';⌈/V
'MEAN           ';MEAN V
'SD             ';SD V
∇
∇R←ZSCORE V
R←(V-MEAN V)÷SD V
∇
∇R←RANK V;E;O;N
⍝ THE PLACE OF EACH VALUE IN ASCENDING ORDER; TIES SHARE THE MEAN OF
⍝ THEIR PLACES. E IS WHICH VALUES ARE EQUAL, O THE PLACES WITHOUT
⍝ TIES. HOWRANK.
V←,V
N←×/⍴V
O←⍋⍋V
E←V∘.=V
R←(+/E×(N,N)⍴O)÷+/E
∇
∇R←FREQ V;U
⍝ THE DISTINCT VALUES IN ASCENDING ORDER, AND HOW OFTEN EACH OCCURS:
⍝ A MATRIX OF TWO COLUMNS.
V←,V
U←((⍳⍴V)=V⍳V)/V
U←U[⍋U]
R←⍉(2,⍴U)⍴U,+/U∘.=V
∇
∇N HIST V;L;H;W;B;C;M;S
⍝ N BINS OF EQUAL WIDTH FROM THE LEAST TO THE GREATEST; A VALUE ON
⍝ AN EDGE GOES IN THE BIN ABOVE, THE GREATEST IN THE LAST. ROWS OF
⍝ STARS, SCALED TO 60 WHEN A COUNT IS LARGER. HOWHIST.
V←,V
L←⌊/V
H←⌈/V
→(L<H)/SPREAD
N←1
H←L+1
SPREAD:W←(H-L)÷N
'BIN EDGES: ';L+W×¯1+⍳N+1
B←1⌈N⌊⌈(V-L)÷W
C←+/(⍳N)∘.=B
M←⌈/C
S←1
→(M≤60)/DRAW
S←M÷60
'EACH * IS ';S
DRAW:C←⌊0.5+C÷S
' *'[1+C∘.≥⍳1⌈⌈/C]
∇
